services:
  postgres:
    container_name: postgres
    image: postgres:16.6-alpine3.21
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
  # flaresolverr:
  #   container_name: flaresolverr
  #   image: ghcr.io/flaresolverr/flaresolverr:v3.3.20
  #   env_file:
  #     - .env
  #   environment:
  #     - LOG_LEVEL=${LOG_LEVEL:-verbose}
  #     - LOG_HTML=${LOG_HTML:-false}
  #     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  #     - TZ=Asia/Jakarta
  #   ports:
  #     - "${PORT:-8191}:8191"
  #   restart: unless-stopped
  n8n:
    container_name: n8n
    image: n8nio/n8n:stable
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    # environment:
    #   - N8N_SSL_KEY=/certs/mitmproxy-ca.pem
    #   - N8N_SSL_CERT=/certs/mitmproxy-ca.pem
    volumes:
      - n8n:/home/node/.n8n
      - ./local-files/:/files/
      - ./mitmproxy/:/certs/
  # nginx:
  #   container_name: nginx
  #   image: nginx:1.27.3-alpine-slim
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "service", "nginx", "status"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 20s
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - nginx:/var/logs/nginx/
  #   ports:
  #     - 8089:80
  # squid:
  #   image: ubuntu/squid:6.1-23.10_beta
  #   container_name: squid
  #   command: ["-f", "/etc/squid/squid.conf", "-NYC"]
  #   ports:
  #     - "3128:3128"
  #   volumes:
  #     - ./squid.conf:/etc/squid/squid.conf
  #   restart: unless-stopped
  mitmproxy:
    image: mitmproxy/mitmproxy
    container_name: mitmproxy
    command:
      [
        "mitmweb",
        "--web-host",
        "0.0.0.0",
        "--ssl-insecure",
        "--modify-headers=/~q/User-Agent/Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0",
        "--modify-headers=/~q/Host/idx.co.id",
        "--modify-headers=/~q/user-agent/Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0",
        "--modify-headers=/~q/Referer/https://www.idx.co.id/id/perusahaan-tercatat/keterbukaan-informasi/",
        '--modify-headers=/~q/sec-ch-ua-platform/"Android"',
      ]
    tty: true
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./mitmproxy/:/home/mitmproxy/.mitmproxy

volumes:
  n8n:
  postgres:
  nginx:

networks:
  bloodhound:
    name: bloodhound
