# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
include:
  - ./docker-compose-dependency.yaml
  - ./docker-compose-observability.yaml
# services:
