services:
  postgres:
    image: postgres:18.3-trixie
    restart: always
    environment:
      TZ: "Asia/Jakarta"
      PGTZ: "Asia/Jakarta"
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
