acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16 
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7 
acl localnet src fe80::/10 

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777


include /etc/squid/conf.d/*.conf
http_access allow all
http_port 3128

coredump_dir /var/spool/squid

refresh_pattern ^ftp: 1440 20% 10080
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
refresh_pattern \/Release(|\.gpg)$ 0 0% 0 refresh-ims
refresh_pattern \/InRelease$ 0 0% 0 refresh-ims
refresh_pattern \/(Translation-.*)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
refresh_pattern . 0 20% 4320

dns_nameservers 8.8.8.8

request_header_access User-Agent deny all
request_header_access user-agent deny all
request_header_access Host deny all
request_header_replace User-Agent 'Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0'
request_header_replace user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0'
request_header_replace Host 'idx.co.id'

#request_header_access Referer 'https://idx.co.id/id/perusahaan-tercatat/keterbukaan-informasi/'
#request_header_access Accept 'application/json, text/plain, */*'
#request_header_access Accept-Language 'en-US,en;q=0.5'
#request_header_access Accept-Encoding 'gzip, deflate, br, zstd'
#request_header_access Sec-Fetch-Dest 'empty'
#request_header_access Sec-Fetch-Mode 'cors'
#request_header_access Sec-Fetch-Site 'same-origin'

ssl_bump client-first all
always_direct allow all
