//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Announcements struct {
	ID        uuid.UUID `sql:"primary_key" json:"id"`
	IdxID     string    `json:"idx_id"`
	StockCode string    `json:"stock_code"`
	Title     string    `json:"title"`
	Date      time.Time `json:"date"`
	CreatedAt time.Time `json:"created_at"`
}
