//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Attachments struct {
	ID                uuid.UUID `sql:"primary_key" json:"id"`
	IdxAnnouncementID string    `json:"idx_announcement_id"`
	IdxURL            string    `json:"idx_url"`
	Error             string    `json:"error"`
	OriginalFilename  string    `json:"original_filename"`
	Filename          string    `json:"filename"`
	Checksum          string    `json:"checksum"`
	StoragePath       string    `json:"storage_path"`
	Title             string    `json:"title"`
	StockCode         string    `json:"stock_code"`
	IsDownloaded      bool      `json:"is_downloaded"`
	IsProcessing      bool      `json:"is_processing"`
	Date              time.Time `json:"date"`
	UploadedAt        time.Time `json:"uploaded_at"`
}
