//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Attachments struct {
	ID                uuid.UUID `sql:"primary_key" json:"id"`
	IdxAnnouncementID string    `json:"idx_announcement_id"`
	OriginalFilename  string    `json:"original_filename"`
	Checksum          string    `json:"checksum"`
	StoragePath       string    `json:"storage_path"`
	UploadedAt        time.Time `json:"uploaded_at"`
}
