//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BrokerTransactions struct {
	ID           uuid.UUID `sql:"primary_key" json:"id"`
	SummaryID    uuid.UUID `json:"summary_id"`
	Symbol       string    `json:"symbol"`
	InvestorType string    `json:"investor_type"`
	Side         string    `json:"side"`
	BrokerCode   string    `json:"broker_code"`
	Frequency    int32     `json:"frequency"`
	Lots         int64     `json:"lots"`
	AvgPrice     float64   `json:"avg_price"`
	TradeDate    time.Time `json:"trade_date"`
}
