//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BrokerTransactions struct {
	ID           uuid.UUID `sql:"primary_key"`
	SummaryID    uuid.UUID
	Symbol       string
	InvestorType string
	Side         string
	BrokerCode   string
	Frequency    int32
	Lots         int64
	AvgPrice     float64
	TradeDate    time.Time
}
