//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ExtractedAttachments struct {
	ID                uuid.UUID `sql:"primary_key" json:"id"`
	AttachmentID      uuid.UUID `json:"attachment_id"`
	IdxAnnouncementID string    `json:"idx_announcement_id"`
	Title             string    `json:"title"`
	StockCode         string    `json:"stock_code"`
	ExtractedAt       time.Time `json:"extracted_at"`
	MinioKey          string    `json:"minio_key"`
	Metadata          *string   `json:"metadata"`
}
