//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type MarketDetectorSummaries struct {
	ID            uuid.UUID `sql:"primary_key" json:"id"`
	Symbol        string    `json:"symbol"`
	AccdistStatus string    `json:"accdist_status"`
	TotalValue    float64   `json:"total_value"`
	CreatedAt     time.Time `json:"created_at"`
	TradeDate     time.Time `json:"trade_date"`
}
