service:
  flush: 1
  # parsers_file: /fluent-bit/etc/parsers.yaml
  log_level: info
  http_server: true
  hot_reload: on

parsers:
  - name: json
    format: json
  - name: logfmt
    format: logfmt
  - name: docker
    format: json
    time_key: time
    time_keep: true
    decode_field_as: escaped_utf8 log do_next json

pipeline:
  inputs:
    - name: tail
      path: /var/logs/bloodhound/bloodhound.log
      tag: app.bloodhound
      parser: json
      buffer_chunk_size: 8M
      buffer_max_size: 16M
      db: bloodhound
    - name: tail
      path: /var/logs/bloodhound/bloodhound-dev.log
      tag: app.bloodhound
      parser: logfmt
      buffer_chunk_size: 8M
      buffer_max_size: 16M
      db: bloodhound-dev
    - name: forward
      listen: 0.0.0.0
      port: 24224
      tag_prefix: forward.
    - name: fluentbit_metrics
      tag: fluentbit.metrics
      scrape_interval: 5
    - name: health
      host: 0.0.0.0
      interval_nsec: 0
      interval_sec: 5
      port: 80
      tag: fluentbit.health
  filters:
    - name: parser
      key_name: log
      match: forward.*
      parser: docker
      reserve_data: on
  outputs:
    - name: stdout
      format: json_lines
      json_date_format: iso8601
      json_date_key: time
      match: "*"
    - name: prometheus_exporter
      match: fluentbit.metrics
      host: 0.0.0.0
      port: 2021
    - name: loki
      host: loki
      labels: service=fluentbit
      match: "fluentbit.*"
      port: 3100
    - name: loki
      host: loki
      labels: service=bloodhound
      match: app.bloodhound
      port: 3100
    # - name: file
    #   path: /var/logs/fluentbit
    #   file: fluentbit.log
    #   match: "*"
