//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AnalyzedCompanies struct {
	ID                    uuid.UUID `sql:"primary_key"`
	CompanyID             *uuid.UUID
	ExtractedAttachmentID *uuid.UUID
	Path                  *string
	CreatedAt             *time.Time
}
