//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AttachmentType string

const (
	AttachmentType_PublicExpose            AttachmentType = "public_expose"
	AttachmentType_CorpAction              AttachmentType = "corp_action"
	AttachmentType_EarningCall             AttachmentType = "earning_call"
	AttachmentType_Pers                    AttachmentType = "pers"
	AttachmentType_SharesOwnershipsUpdate  AttachmentType = "shares_ownerships_update"
	AttachmentType_SharesOutstandingUpdate AttachmentType = "shares_outstanding_update"
	AttachmentType_Others                  AttachmentType = "others"
)

var AttachmentTypeAllValues = []AttachmentType{
	AttachmentType_PublicExpose,
	AttachmentType_CorpAction,
	AttachmentType_EarningCall,
	AttachmentType_Pers,
	AttachmentType_SharesOwnershipsUpdate,
	AttachmentType_SharesOutstandingUpdate,
	AttachmentType_Others,
}

func (e *AttachmentType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "public_expose":
		*e = AttachmentType_PublicExpose
	case "corp_action":
		*e = AttachmentType_CorpAction
	case "earning_call":
		*e = AttachmentType_EarningCall
	case "pers":
		*e = AttachmentType_Pers
	case "shares_ownerships_update":
		*e = AttachmentType_SharesOwnershipsUpdate
	case "shares_outstanding_update":
		*e = AttachmentType_SharesOutstandingUpdate
	case "others":
		*e = AttachmentType_Others
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AttachmentType enum")
	}

	return nil
}

func (e AttachmentType) String() string {
	return string(e)
}
