//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type IndustryType string

const (
	IndustryType_AplikasiAmpersandJasaInternet                      IndustryType = "Aplikasi & Jasa Internet"
	IndustryType_Asuransi                                           IndustryType = "Asuransi"
	IndustryType_Bank                                               IndustryType = "Bank"
	IndustryType_BarangElektronikKonsumen                           IndustryType = "Barang Elektronik Konsumen"
	IndustryType_BarangKimia                                        IndustryType = "Barang Kimia"
	IndustryType_BarangRumahTangga                                  IndustryType = "Barang Rumah Tangga"
	IndustryType_BatuBara                                           IndustryType = "Batu Bara"
	IndustryType_DepartmentStore                                    IndustryType = "Department Store"
	IndustryType_DistributorBarangKonsumen                          IndustryType = "Distributor Barang Konsumen"
	IndustryType_Farmasi                                            IndustryType = "Farmasi"
	IndustryType_HiburanAmpersandFilm                               IndustryType = "Hiburan & Film"
	IndustryType_JasaInvestasi                                      IndustryType = "Jasa Investasi"
	IndustryType_JasaKomersial                                      IndustryType = "Jasa Komersial"
	IndustryType_JasaAmpersandKonsultanTi                           IndustryType = "Jasa & Konsultan TI"
	IndustryType_JasaProfesional                                    IndustryType = "Jasa Profesional"
	IndustryType_JasaTelekomunikasi                                 IndustryType = "Jasa Telekomunikasi"
	IndustryType_JasaTelekomunikasiNirkabel                         IndustryType = "Jasa Telekomunikasi Nirkabel"
	IndustryType_Kelistrikan                                        IndustryType = "Kelistrikan"
	IndustryType_KomponenOtomotif                                   IndustryType = "Komponen Otomotif"
	IndustryType_KonstruksiBangunan                                 IndustryType = "Konstruksi Bangunan"
	IndustryType_LogamAmpersandMineral                              IndustryType = "Logam & Mineral"
	IndustryType_LogistikAmpersandPengantaran                       IndustryType = "Logistik & Pengantaran"
	IndustryType_MakananOlahan                                      IndustryType = "Makanan Olahan"
	IndustryType_MaskapaiPenerbangan                                IndustryType = "Maskapai Penerbangan"
	IndustryType_MaterialKonstruksi                                 IndustryType = "Material Konstruksi"
	IndustryType_Media                                              IndustryType = "Media"
	IndustryType_Mesin                                              IndustryType = "Mesin"
	IndustryType_Minuman                                            IndustryType = "Minuman"
	IndustryType_MinyakAmpersandGas                                 IndustryType = "Minyak & Gas"
	IndustryType_OperatorInfrastrukturTransportasi                  IndustryType = "Operator Infrastruktur Transportasi"
	IndustryType_PakaianAmpersandBarangMewah                        IndustryType = "Pakaian & Barang Mewah"
	IndustryType_PariwisataAmpersandRekreasi                        IndustryType = "Pariwisata & Rekreasi"
	IndustryType_PembiayaanKonsumen                                 IndustryType = "Pembiayaan Konsumen"
	IndustryType_PendidikanAmpersandJasaPenunjang                   IndustryType = "Pendidikan & Jasa Penunjang"
	IndustryType_PendukungMinyakCommaGasAmpersandBatuBara           IndustryType = "Pendukung Minyak, Gas & Batu Bara"
	IndustryType_PengangkutanDaratPenumpang                         IndustryType = "Pengangkutan Darat Penumpang"
	IndustryType_PengelolaAmpersandPengembangRealEstat              IndustryType = "Pengelola & Pengembang Real Estat"
	IndustryType_PenyediaJasaKesehatan                              IndustryType = "Penyedia Jasa Kesehatan"
	IndustryType_PeralatanEnergiAlternatif                          IndustryType = "Peralatan Energi Alternatif"
	IndustryType_PeralatanJaringan                                  IndustryType = "Peralatan Jaringan"
	IndustryType_PeralatanOlahRagaAmpersandBarangHobi               IndustryType = "Peralatan Olah Raga & Barang Hobi"
	IndustryType_PeralatanAmpersandPerlengkapanKesehatan            IndustryType = "Peralatan & Perlengkapan Kesehatan"
	IndustryType_PerangkatCommaInstrumenAmpersandKomponenElektronik IndustryType = "Perangkat, Instrumen & Komponen Elektronik"
	IndustryType_PerangkatKomputer                                  IndustryType = "Perangkat Komputer"
	IndustryType_PerangkatLunak                                     IndustryType = "Perangkat Lunak"
	IndustryType_PerdaganganAnekaBarangPerindustrian                IndustryType = "Perdagangan Aneka Barang Perindustrian"
	IndustryType_PerdaganganRitelBarangPrimer                       IndustryType = "Perdagangan Ritel Barang Primer"
	IndustryType_PerhutananAmpersandKertas                          IndustryType = "Perhutanan & Kertas"
	IndustryType_PerusahaanHoldingAmpersandInvestasi                IndustryType = "Perusahaan Holding & Investasi"
	IndustryType_PerusahaanHoldingMultiSektor                       IndustryType = "Perusahaan Holding Multi-sektor"
	IndustryType_ProdukMakananPertanian                             IndustryType = "Produk Makanan Pertanian"
	IndustryType_ProdukPerawatanTubuh                               IndustryType = "Produk Perawatan Tubuh"
	IndustryType_ProdukAmpersandPerlengkapanBangunan                IndustryType = "Produk & Perlengkapan Bangunan"
	IndustryType_RitelKhusus                                        IndustryType = "Ritel Khusus"
	IndustryType_Rokok                                              IndustryType = "Rokok"
	IndustryType_UtilitasGas                                        IndustryType = "Utilitas Gas"
	IndustryType_UtilitasListrik                                    IndustryType = "Utilitas Listrik"
	IndustryType_WadahAmpersandKemasan                              IndustryType = "Wadah & Kemasan"
	IndustryType_Others                                             IndustryType = "Others"
)

var IndustryTypeAllValues = []IndustryType{
	IndustryType_AplikasiAmpersandJasaInternet,
	IndustryType_Asuransi,
	IndustryType_Bank,
	IndustryType_BarangElektronikKonsumen,
	IndustryType_BarangKimia,
	IndustryType_BarangRumahTangga,
	IndustryType_BatuBara,
	IndustryType_DepartmentStore,
	IndustryType_DistributorBarangKonsumen,
	IndustryType_Farmasi,
	IndustryType_HiburanAmpersandFilm,
	IndustryType_JasaInvestasi,
	IndustryType_JasaKomersial,
	IndustryType_JasaAmpersandKonsultanTi,
	IndustryType_JasaProfesional,
	IndustryType_JasaTelekomunikasi,
	IndustryType_JasaTelekomunikasiNirkabel,
	IndustryType_Kelistrikan,
	IndustryType_KomponenOtomotif,
	IndustryType_KonstruksiBangunan,
	IndustryType_LogamAmpersandMineral,
	IndustryType_LogistikAmpersandPengantaran,
	IndustryType_MakananOlahan,
	IndustryType_MaskapaiPenerbangan,
	IndustryType_MaterialKonstruksi,
	IndustryType_Media,
	IndustryType_Mesin,
	IndustryType_Minuman,
	IndustryType_MinyakAmpersandGas,
	IndustryType_OperatorInfrastrukturTransportasi,
	IndustryType_PakaianAmpersandBarangMewah,
	IndustryType_PariwisataAmpersandRekreasi,
	IndustryType_PembiayaanKonsumen,
	IndustryType_PendidikanAmpersandJasaPenunjang,
	IndustryType_PendukungMinyakCommaGasAmpersandBatuBara,
	IndustryType_PengangkutanDaratPenumpang,
	IndustryType_PengelolaAmpersandPengembangRealEstat,
	IndustryType_PenyediaJasaKesehatan,
	IndustryType_PeralatanEnergiAlternatif,
	IndustryType_PeralatanJaringan,
	IndustryType_PeralatanOlahRagaAmpersandBarangHobi,
	IndustryType_PeralatanAmpersandPerlengkapanKesehatan,
	IndustryType_PerangkatCommaInstrumenAmpersandKomponenElektronik,
	IndustryType_PerangkatKomputer,
	IndustryType_PerangkatLunak,
	IndustryType_PerdaganganAnekaBarangPerindustrian,
	IndustryType_PerdaganganRitelBarangPrimer,
	IndustryType_PerhutananAmpersandKertas,
	IndustryType_PerusahaanHoldingAmpersandInvestasi,
	IndustryType_PerusahaanHoldingMultiSektor,
	IndustryType_ProdukMakananPertanian,
	IndustryType_ProdukPerawatanTubuh,
	IndustryType_ProdukAmpersandPerlengkapanBangunan,
	IndustryType_RitelKhusus,
	IndustryType_Rokok,
	IndustryType_UtilitasGas,
	IndustryType_UtilitasListrik,
	IndustryType_WadahAmpersandKemasan,
	IndustryType_Others,
}

func (e *IndustryType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Aplikasi & Jasa Internet":
		*e = IndustryType_AplikasiAmpersandJasaInternet
	case "Asuransi":
		*e = IndustryType_Asuransi
	case "Bank":
		*e = IndustryType_Bank
	case "Barang Elektronik Konsumen":
		*e = IndustryType_BarangElektronikKonsumen
	case "Barang Kimia":
		*e = IndustryType_BarangKimia
	case "Barang Rumah Tangga":
		*e = IndustryType_BarangRumahTangga
	case "Batu Bara":
		*e = IndustryType_BatuBara
	case "Department Store":
		*e = IndustryType_DepartmentStore
	case "Distributor Barang Konsumen":
		*e = IndustryType_DistributorBarangKonsumen
	case "Farmasi":
		*e = IndustryType_Farmasi
	case "Hiburan & Film":
		*e = IndustryType_HiburanAmpersandFilm
	case "Jasa Investasi":
		*e = IndustryType_JasaInvestasi
	case "Jasa Komersial":
		*e = IndustryType_JasaKomersial
	case "Jasa & Konsultan TI":
		*e = IndustryType_JasaAmpersandKonsultanTi
	case "Jasa Profesional":
		*e = IndustryType_JasaProfesional
	case "Jasa Telekomunikasi":
		*e = IndustryType_JasaTelekomunikasi
	case "Jasa Telekomunikasi Nirkabel":
		*e = IndustryType_JasaTelekomunikasiNirkabel
	case "Kelistrikan":
		*e = IndustryType_Kelistrikan
	case "Komponen Otomotif":
		*e = IndustryType_KomponenOtomotif
	case "Konstruksi Bangunan":
		*e = IndustryType_KonstruksiBangunan
	case "Logam & Mineral":
		*e = IndustryType_LogamAmpersandMineral
	case "Logistik & Pengantaran":
		*e = IndustryType_LogistikAmpersandPengantaran
	case "Makanan Olahan":
		*e = IndustryType_MakananOlahan
	case "Maskapai Penerbangan":
		*e = IndustryType_MaskapaiPenerbangan
	case "Material Konstruksi":
		*e = IndustryType_MaterialKonstruksi
	case "Media":
		*e = IndustryType_Media
	case "Mesin":
		*e = IndustryType_Mesin
	case "Minuman":
		*e = IndustryType_Minuman
	case "Minyak & Gas":
		*e = IndustryType_MinyakAmpersandGas
	case "Operator Infrastruktur Transportasi":
		*e = IndustryType_OperatorInfrastrukturTransportasi
	case "Pakaian & Barang Mewah":
		*e = IndustryType_PakaianAmpersandBarangMewah
	case "Pariwisata & Rekreasi":
		*e = IndustryType_PariwisataAmpersandRekreasi
	case "Pembiayaan Konsumen":
		*e = IndustryType_PembiayaanKonsumen
	case "Pendidikan & Jasa Penunjang":
		*e = IndustryType_PendidikanAmpersandJasaPenunjang
	case "Pendukung Minyak, Gas & Batu Bara":
		*e = IndustryType_PendukungMinyakCommaGasAmpersandBatuBara
	case "Pengangkutan Darat Penumpang":
		*e = IndustryType_PengangkutanDaratPenumpang
	case "Pengelola & Pengembang Real Estat":
		*e = IndustryType_PengelolaAmpersandPengembangRealEstat
	case "Penyedia Jasa Kesehatan":
		*e = IndustryType_PenyediaJasaKesehatan
	case "Peralatan Energi Alternatif":
		*e = IndustryType_PeralatanEnergiAlternatif
	case "Peralatan Jaringan":
		*e = IndustryType_PeralatanJaringan
	case "Peralatan Olah Raga & Barang Hobi":
		*e = IndustryType_PeralatanOlahRagaAmpersandBarangHobi
	case "Peralatan & Perlengkapan Kesehatan":
		*e = IndustryType_PeralatanAmpersandPerlengkapanKesehatan
	case "Perangkat, Instrumen & Komponen Elektronik":
		*e = IndustryType_PerangkatCommaInstrumenAmpersandKomponenElektronik
	case "Perangkat Komputer":
		*e = IndustryType_PerangkatKomputer
	case "Perangkat Lunak":
		*e = IndustryType_PerangkatLunak
	case "Perdagangan Aneka Barang Perindustrian":
		*e = IndustryType_PerdaganganAnekaBarangPerindustrian
	case "Perdagangan Ritel Barang Primer":
		*e = IndustryType_PerdaganganRitelBarangPrimer
	case "Perhutanan & Kertas":
		*e = IndustryType_PerhutananAmpersandKertas
	case "Perusahaan Holding & Investasi":
		*e = IndustryType_PerusahaanHoldingAmpersandInvestasi
	case "Perusahaan Holding Multi-sektor":
		*e = IndustryType_PerusahaanHoldingMultiSektor
	case "Produk Makanan Pertanian":
		*e = IndustryType_ProdukMakananPertanian
	case "Produk Perawatan Tubuh":
		*e = IndustryType_ProdukPerawatanTubuh
	case "Produk & Perlengkapan Bangunan":
		*e = IndustryType_ProdukAmpersandPerlengkapanBangunan
	case "Ritel Khusus":
		*e = IndustryType_RitelKhusus
	case "Rokok":
		*e = IndustryType_Rokok
	case "Utilitas Gas":
		*e = IndustryType_UtilitasGas
	case "Utilitas Listrik":
		*e = IndustryType_UtilitasListrik
	case "Wadah & Kemasan":
		*e = IndustryType_WadahAmpersandKemasan
	case "Others":
		*e = IndustryType_Others
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for IndustryType enum")
	}

	return nil
}

func (e IndustryType) String() string {
	return string(e)
}
