//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type SectorType string

const (
	SectorType_BarangBaku                    SectorType = "Barang Baku"
	SectorType_BarangKonsumenNonPrimer       SectorType = "Barang Konsumen Non-Primer"
	SectorType_BarangKonsumenPrimer          SectorType = "Barang Konsumen Primer"
	SectorType_Energi                        SectorType = "Energi"
	SectorType_Infrastruktur                 SectorType = "Infrastruktur"
	SectorType_Kesehatan                     SectorType = "Kesehatan"
	SectorType_Keuangan                      SectorType = "Keuangan"
	SectorType_Perindustrian                 SectorType = "Perindustrian"
	SectorType_PropertiAmpersandRealEstat    SectorType = "Properti & Real Estat"
	SectorType_Teknologi                     SectorType = "Teknologi"
	SectorType_TransportasiAmpersandLogistik SectorType = "Transportasi & Logistik"
	SectorType_Others                        SectorType = "Others"
)

var SectorTypeAllValues = []SectorType{
	SectorType_BarangBaku,
	SectorType_BarangKonsumenNonPrimer,
	SectorType_BarangKonsumenPrimer,
	SectorType_Energi,
	SectorType_Infrastruktur,
	SectorType_Kesehatan,
	SectorType_Keuangan,
	SectorType_Perindustrian,
	SectorType_PropertiAmpersandRealEstat,
	SectorType_Teknologi,
	SectorType_TransportasiAmpersandLogistik,
	SectorType_Others,
}

func (e *SectorType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Barang Baku":
		*e = SectorType_BarangBaku
	case "Barang Konsumen Non-Primer":
		*e = SectorType_BarangKonsumenNonPrimer
	case "Barang Konsumen Primer":
		*e = SectorType_BarangKonsumenPrimer
	case "Energi":
		*e = SectorType_Energi
	case "Infrastruktur":
		*e = SectorType_Infrastruktur
	case "Kesehatan":
		*e = SectorType_Kesehatan
	case "Keuangan":
		*e = SectorType_Keuangan
	case "Perindustrian":
		*e = SectorType_Perindustrian
	case "Properti & Real Estat":
		*e = SectorType_PropertiAmpersandRealEstat
	case "Teknologi":
		*e = SectorType_Teknologi
	case "Transportasi & Logistik":
		*e = SectorType_TransportasiAmpersandLogistik
	case "Others":
		*e = SectorType_Others
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for SectorType enum")
	}

	return nil
}

func (e SectorType) String() string {
	return string(e)
}
