//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type SubIndustryType string

const (
	SubIndustryType_AgenPerjalanan                                           SubIndustryType = "Agen Perjalanan"
	SubIndustryType_AlasKaki                                                 SubIndustryType = "Alas Kaki"
	SubIndustryType_Alumunium                                                SubIndustryType = "Alumunium"
	SubIndustryType_AplikasiAmpersandJasaInternet                            SubIndustryType = "Aplikasi & Jasa Internet"
	SubIndustryType_AsuransiJiwa                                             SubIndustryType = "Asuransi Jiwa"
	SubIndustryType_AsuransiUmum                                             SubIndustryType = "Asuransi Umum"
	SubIndustryType_BajaAmpersandBesi                                        SubIndustryType = "Baja & Besi"
	SubIndustryType_Ban                                                      SubIndustryType = "Ban"
	SubIndustryType_Bank                                                     SubIndustryType = "Bank"
	SubIndustryType_BankInvestasiAmpersandPerantaraPerdagangan               SubIndustryType = "Bank Investasi & Perantara Perdagangan"
	SubIndustryType_BarangElektronikKonsumen                                 SubIndustryType = "Barang Elektronik Konsumen"
	SubIndustryType_BarangKimiaDasar                                         SubIndustryType = "Barang Kimia Dasar"
	SubIndustryType_BarangKimiaKhusus                                        SubIndustryType = "Barang Kimia Khusus"
	SubIndustryType_BarangKimiaPertanian                                     SubIndustryType = "Barang Kimia Pertanian"
	SubIndustryType_DepartmentStore                                          SubIndustryType = "Department Store"
	SubIndustryType_DistribusiBatuBara                                       SubIndustryType = "Distribusi Batu Bara"
	SubIndustryType_DistributorBarangKonsumen                                SubIndustryType = "Distributor Barang Konsumen"
	SubIndustryType_Emas                                                     SubIndustryType = "Emas"
	SubIndustryType_Farmasi                                                  SubIndustryType = "Farmasi"
	SubIndustryType_FasilitasRekreasiAmpersandOlahRaga                       SubIndustryType = "Fasilitas Rekreasi & Olah Raga"
	SubIndustryType_HiburanAmpersandFilm                                     SubIndustryType = "Hiburan & Film"
	SubIndustryType_HotelCommaResorAmpersandKapalPesiar                      SubIndustryType = "Hotel, Resor & Kapal Pesiar"
	SubIndustryType_IkanCommaDagingAmpersandProdukUnggas                     SubIndustryType = "Ikan, Daging & Produk Unggas"
	SubIndustryType_JasaAmpersandKonsultanTi                                 SubIndustryType = "Jasa & Konsultan TI"
	SubIndustryType_JasaPendidikan                                           SubIndustryType = "Jasa Pendidikan"
	SubIndustryType_JasaPendukungBisnis                                      SubIndustryType = "Jasa Pendukung Bisnis"
	SubIndustryType_JasaPenelitianAmpersandKonsultasi                        SubIndustryType = "Jasa Penelitian & Konsultasi"
	SubIndustryType_JasaPengeboranMinyakAmpersandGas                         SubIndustryType = "Jasa Pengeboran Minyak & Gas"
	SubIndustryType_JasaPengelolaanLingkunganAmpersandSarana                 SubIndustryType = "Jasa Pengelolaan Lingkungan & Sarana"
	SubIndustryType_JasaAmpersandPerlengkapanMinyakCommaGasAmpersandBatuBara SubIndustryType = "Jasa & Perlengkapan Minyak, Gas & Batu Bara"
	SubIndustryType_JasaPersonalia                                           SubIndustryType = "Jasa Personalia"
	SubIndustryType_JasaRealEstat                                            SubIndustryType = "Jasa Real Estat"
	SubIndustryType_JasaTelekomunikasiKabel                                  SubIndustryType = "Jasa Telekomunikasi Kabel"
	SubIndustryType_JasaTelekomunikasiNirkabel                               SubIndustryType = "Jasa Telekomunikasi Nirkabel"
	SubIndustryType_JasaTelekomunikasiTerintegrasi                           SubIndustryType = "Jasa Telekomunikasi Terintegrasi"
	SubIndustryType_Kayu                                                     SubIndustryType = "Kayu"
	SubIndustryType_Kertas                                                   SubIndustryType = "Kertas"
	SubIndustryType_KomponenAmpersandPeralatanKelistrikan                    SubIndustryType = "Komponen & Peralatan Kelistrikan"
	SubIndustryType_KonstruksiBangunan                                       SubIndustryType = "Konstruksi Bangunan"
	SubIndustryType_LogamAmpersandMineralLainnya                             SubIndustryType = "Logam & Mineral Lainnya"
	SubIndustryType_LogistikAmpersandPengantaran                             SubIndustryType = "Logistik & Pengantaran"
	SubIndustryType_MakananOlahan                                            SubIndustryType = "Makanan Olahan"
	SubIndustryType_ManajemenInvestasi                                       SubIndustryType = "Manajemen Investasi"
	SubIndustryType_MaskapaiPenerbangan                                      SubIndustryType = "Maskapai Penerbangan"
	SubIndustryType_MaterialKonstruksi                                       SubIndustryType = "Material Konstruksi"
	SubIndustryType_MesinAmpersandKomponenPerindustrian                      SubIndustryType = "Mesin & Komponen Perindustrian"
	SubIndustryType_MesinKonstruksiAmpersandKendaraanBerat                   SubIndustryType = "Mesin Konstruksi & Kendaraan Berat"
	SubIndustryType_MinumanKeras                                             SubIndustryType = "Minuman Keras"
	SubIndustryType_MinumanRingan                                            SubIndustryType = "Minuman Ringan"
	SubIndustryType_OperatorBandarUdara                                      SubIndustryType = "Operator Bandar Udara"
	SubIndustryType_OperatorJalanTolAmpersandRel                             SubIndustryType = "Operator Jalan Tol & Rel"
	SubIndustryType_OperatorPelabuhan                                        SubIndustryType = "Operator Pelabuhan"
	SubIndustryType_PakaianCommaAksesorisCommaAmpersandTas                   SubIndustryType = "Pakaian, Aksesoris, & Tas"
	SubIndustryType_PembiayaanKonsumen                                       SubIndustryType = "Pembiayaan Konsumen"
	SubIndustryType_Penerbitan                                               SubIndustryType = "Penerbitan"
	SubIndustryType_PengembangAmpersandOperatorRealEstat                     SubIndustryType = "Pengembang & Operator Real Estat"
	SubIndustryType_PenyediaAmpersandDistribusiPerlengkapanKesehatan         SubIndustryType = "Penyedia & Distribusi Perlengkapan Kesehatan"
	SubIndustryType_PenyediaJasaKesehatan                                    SubIndustryType = "Penyedia Jasa Kesehatan"
	SubIndustryType_Penyiaran                                                SubIndustryType = "Penyiaran"
	SubIndustryType_PenyiaranBerbayar                                        SubIndustryType = "Penyiaran Berbayar"
	SubIndustryType_PenyimpananAmpersandDistribusiMinyakAmpersandGas         SubIndustryType = "Penyimpanan & Distribusi Minyak & Gas"
	SubIndustryType_PeralatanEnergiAlternatif                                SubIndustryType = "Peralatan Energi Alternatif"
	SubIndustryType_PeralatanJaringan                                        SubIndustryType = "Peralatan Jaringan"
	SubIndustryType_PeralatanKantor                                          SubIndustryType = "Peralatan Kantor"
	SubIndustryType_PeralatanOlahRagaAmpersandBarangHobi                     SubIndustryType = "Peralatan Olah Raga & Barang Hobi"
	SubIndustryType_PeralatanRumahTangga                                     SubIndustryType = "Peralatan Rumah Tangga"
	SubIndustryType_PerangkatAmpersandInstrumenElektronik                    SubIndustryType = "Perangkat & Instrumen Elektronik"
	SubIndustryType_PerangkatKomputer                                        SubIndustryType = "Perangkat Komputer"
	SubIndustryType_PerangkatLunak                                           SubIndustryType = "Perangkat Lunak"
	SubIndustryType_PercetakanKomersial                                      SubIndustryType = "Percetakan Komersial"
	SubIndustryType_PerdaganganAnekaBarangPerindustrian                      SubIndustryType = "Perdagangan Aneka Barang Perindustrian"
	SubIndustryType_Periklanan                                               SubIndustryType = "Periklanan"
	SubIndustryType_PerkebunanAmpersandTanamanPangan                         SubIndustryType = "Perkebunan & Tanaman Pangan"
	SubIndustryType_PerlengkapanRumahTangga                                  SubIndustryType = "Perlengkapan Rumah Tangga"
	SubIndustryType_PerusahaanHoldingKeuangan                                SubIndustryType = "Perusahaan Holding Keuangan"
	SubIndustryType_PerusahaanHoldingMultiSektor                             SubIndustryType = "Perusahaan Holding Multi-sektor"
	SubIndustryType_PerusahaanInvestasi                                      SubIndustryType = "Perusahaan Investasi"
	SubIndustryType_ProdukHutanLainnya                                       SubIndustryType = "Produk Hutan Lainnya"
	SubIndustryType_ProdukPerawatanTubuh                                     SubIndustryType = "Produk Perawatan Tubuh"
	SubIndustryType_ProdukAmpersandPerlengkapanBangunan                      SubIndustryType = "Produk & Perlengkapan Bangunan"
	SubIndustryType_ProduksiBatuBara                                         SubIndustryType = "Produksi Batu Bara"
	SubIndustryType_ProduksiAmpersandPenyulinganMinyakAmpersandGas           SubIndustryType = "Produksi & Penyulingan Minyak & Gas"
	SubIndustryType_ProdukSusuOlahan                                         SubIndustryType = "Produk Susu Olahan"
	SubIndustryType_ProdusenFurniturRumah                                    SubIndustryType = "Produsen Furnitur Rumah"
	SubIndustryType_Reasuransi                                               SubIndustryType = "Reasuransi"
	SubIndustryType_RitelBarangRumahTangga                                   SubIndustryType = "Ritel Barang Rumah Tangga"
	SubIndustryType_RitelAmpersandDistributorMakanan                         SubIndustryType = "Ritel & Distributor Makanan"
	SubIndustryType_RitelAmpersandDistributorObatObatan                      SubIndustryType = "Ritel & Distributor Obat-obatan"
	SubIndustryType_RitelElektronik                                          SubIndustryType = "Ritel Elektronik"
	SubIndustryType_RitelOtomotif                                            SubIndustryType = "Ritel Otomotif"
	SubIndustryType_RitelPakaianAmpersandTekstil                             SubIndustryType = "Ritel Pakaian & Tekstil"
	SubIndustryType_Rokok                                                    SubIndustryType = "Rokok"
	SubIndustryType_RumahMakan                                               SubIndustryType = "Rumah Makan"
	SubIndustryType_SukuCadangOtomotif                                       SubIndustryType = "Suku Cadang Otomotif"
	SubIndustryType_Supermarket                                              SubIndustryType = "Supermarket"
	SubIndustryType_Tekstil                                                  SubIndustryType = "Tekstil"
	SubIndustryType_Tembaga                                                  SubIndustryType = "Tembaga"
	SubIndustryType_TransportasiJalanan                                      SubIndustryType = "Transportasi Jalanan"
	SubIndustryType_UtilitasGas                                              SubIndustryType = "Utilitas Gas"
	SubIndustryType_UtilitasListrik                                          SubIndustryType = "Utilitas Listrik"
	SubIndustryType_WadahAmpersandKemasan                                    SubIndustryType = "Wadah & Kemasan"
	SubIndustryType_Others                                                   SubIndustryType = "Others"
)

var SubIndustryTypeAllValues = []SubIndustryType{
	SubIndustryType_AgenPerjalanan,
	SubIndustryType_AlasKaki,
	SubIndustryType_Alumunium,
	SubIndustryType_AplikasiAmpersandJasaInternet,
	SubIndustryType_AsuransiJiwa,
	SubIndustryType_AsuransiUmum,
	SubIndustryType_BajaAmpersandBesi,
	SubIndustryType_Ban,
	SubIndustryType_Bank,
	SubIndustryType_BankInvestasiAmpersandPerantaraPerdagangan,
	SubIndustryType_BarangElektronikKonsumen,
	SubIndustryType_BarangKimiaDasar,
	SubIndustryType_BarangKimiaKhusus,
	SubIndustryType_BarangKimiaPertanian,
	SubIndustryType_DepartmentStore,
	SubIndustryType_DistribusiBatuBara,
	SubIndustryType_DistributorBarangKonsumen,
	SubIndustryType_Emas,
	SubIndustryType_Farmasi,
	SubIndustryType_FasilitasRekreasiAmpersandOlahRaga,
	SubIndustryType_HiburanAmpersandFilm,
	SubIndustryType_HotelCommaResorAmpersandKapalPesiar,
	SubIndustryType_IkanCommaDagingAmpersandProdukUnggas,
	SubIndustryType_JasaAmpersandKonsultanTi,
	SubIndustryType_JasaPendidikan,
	SubIndustryType_JasaPendukungBisnis,
	SubIndustryType_JasaPenelitianAmpersandKonsultasi,
	SubIndustryType_JasaPengeboranMinyakAmpersandGas,
	SubIndustryType_JasaPengelolaanLingkunganAmpersandSarana,
	SubIndustryType_JasaAmpersandPerlengkapanMinyakCommaGasAmpersandBatuBara,
	SubIndustryType_JasaPersonalia,
	SubIndustryType_JasaRealEstat,
	SubIndustryType_JasaTelekomunikasiKabel,
	SubIndustryType_JasaTelekomunikasiNirkabel,
	SubIndustryType_JasaTelekomunikasiTerintegrasi,
	SubIndustryType_Kayu,
	SubIndustryType_Kertas,
	SubIndustryType_KomponenAmpersandPeralatanKelistrikan,
	SubIndustryType_KonstruksiBangunan,
	SubIndustryType_LogamAmpersandMineralLainnya,
	SubIndustryType_LogistikAmpersandPengantaran,
	SubIndustryType_MakananOlahan,
	SubIndustryType_ManajemenInvestasi,
	SubIndustryType_MaskapaiPenerbangan,
	SubIndustryType_MaterialKonstruksi,
	SubIndustryType_MesinAmpersandKomponenPerindustrian,
	SubIndustryType_MesinKonstruksiAmpersandKendaraanBerat,
	SubIndustryType_MinumanKeras,
	SubIndustryType_MinumanRingan,
	SubIndustryType_OperatorBandarUdara,
	SubIndustryType_OperatorJalanTolAmpersandRel,
	SubIndustryType_OperatorPelabuhan,
	SubIndustryType_PakaianCommaAksesorisCommaAmpersandTas,
	SubIndustryType_PembiayaanKonsumen,
	SubIndustryType_Penerbitan,
	SubIndustryType_PengembangAmpersandOperatorRealEstat,
	SubIndustryType_PenyediaAmpersandDistribusiPerlengkapanKesehatan,
	SubIndustryType_PenyediaJasaKesehatan,
	SubIndustryType_Penyiaran,
	SubIndustryType_PenyiaranBerbayar,
	SubIndustryType_PenyimpananAmpersandDistribusiMinyakAmpersandGas,
	SubIndustryType_PeralatanEnergiAlternatif,
	SubIndustryType_PeralatanJaringan,
	SubIndustryType_PeralatanKantor,
	SubIndustryType_PeralatanOlahRagaAmpersandBarangHobi,
	SubIndustryType_PeralatanRumahTangga,
	SubIndustryType_PerangkatAmpersandInstrumenElektronik,
	SubIndustryType_PerangkatKomputer,
	SubIndustryType_PerangkatLunak,
	SubIndustryType_PercetakanKomersial,
	SubIndustryType_PerdaganganAnekaBarangPerindustrian,
	SubIndustryType_Periklanan,
	SubIndustryType_PerkebunanAmpersandTanamanPangan,
	SubIndustryType_PerlengkapanRumahTangga,
	SubIndustryType_PerusahaanHoldingKeuangan,
	SubIndustryType_PerusahaanHoldingMultiSektor,
	SubIndustryType_PerusahaanInvestasi,
	SubIndustryType_ProdukHutanLainnya,
	SubIndustryType_ProdukPerawatanTubuh,
	SubIndustryType_ProdukAmpersandPerlengkapanBangunan,
	SubIndustryType_ProduksiBatuBara,
	SubIndustryType_ProduksiAmpersandPenyulinganMinyakAmpersandGas,
	SubIndustryType_ProdukSusuOlahan,
	SubIndustryType_ProdusenFurniturRumah,
	SubIndustryType_Reasuransi,
	SubIndustryType_RitelBarangRumahTangga,
	SubIndustryType_RitelAmpersandDistributorMakanan,
	SubIndustryType_RitelAmpersandDistributorObatObatan,
	SubIndustryType_RitelElektronik,
	SubIndustryType_RitelOtomotif,
	SubIndustryType_RitelPakaianAmpersandTekstil,
	SubIndustryType_Rokok,
	SubIndustryType_RumahMakan,
	SubIndustryType_SukuCadangOtomotif,
	SubIndustryType_Supermarket,
	SubIndustryType_Tekstil,
	SubIndustryType_Tembaga,
	SubIndustryType_TransportasiJalanan,
	SubIndustryType_UtilitasGas,
	SubIndustryType_UtilitasListrik,
	SubIndustryType_WadahAmpersandKemasan,
	SubIndustryType_Others,
}

func (e *SubIndustryType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Agen Perjalanan":
		*e = SubIndustryType_AgenPerjalanan
	case "Alas Kaki":
		*e = SubIndustryType_AlasKaki
	case "Alumunium":
		*e = SubIndustryType_Alumunium
	case "Aplikasi & Jasa Internet":
		*e = SubIndustryType_AplikasiAmpersandJasaInternet
	case "Asuransi Jiwa":
		*e = SubIndustryType_AsuransiJiwa
	case "Asuransi Umum":
		*e = SubIndustryType_AsuransiUmum
	case "Baja & Besi":
		*e = SubIndustryType_BajaAmpersandBesi
	case "Ban":
		*e = SubIndustryType_Ban
	case "Bank":
		*e = SubIndustryType_Bank
	case "Bank Investasi & Perantara Perdagangan":
		*e = SubIndustryType_BankInvestasiAmpersandPerantaraPerdagangan
	case "Barang Elektronik Konsumen":
		*e = SubIndustryType_BarangElektronikKonsumen
	case "Barang Kimia Dasar":
		*e = SubIndustryType_BarangKimiaDasar
	case "Barang Kimia Khusus":
		*e = SubIndustryType_BarangKimiaKhusus
	case "Barang Kimia Pertanian":
		*e = SubIndustryType_BarangKimiaPertanian
	case "Department Store":
		*e = SubIndustryType_DepartmentStore
	case "Distribusi Batu Bara":
		*e = SubIndustryType_DistribusiBatuBara
	case "Distributor Barang Konsumen":
		*e = SubIndustryType_DistributorBarangKonsumen
	case "Emas":
		*e = SubIndustryType_Emas
	case "Farmasi":
		*e = SubIndustryType_Farmasi
	case "Fasilitas Rekreasi & Olah Raga":
		*e = SubIndustryType_FasilitasRekreasiAmpersandOlahRaga
	case "Hiburan & Film":
		*e = SubIndustryType_HiburanAmpersandFilm
	case "Hotel, Resor & Kapal Pesiar":
		*e = SubIndustryType_HotelCommaResorAmpersandKapalPesiar
	case "Ikan, Daging & Produk Unggas":
		*e = SubIndustryType_IkanCommaDagingAmpersandProdukUnggas
	case "Jasa & Konsultan TI":
		*e = SubIndustryType_JasaAmpersandKonsultanTi
	case "Jasa Pendidikan":
		*e = SubIndustryType_JasaPendidikan
	case "Jasa Pendukung Bisnis":
		*e = SubIndustryType_JasaPendukungBisnis
	case "Jasa Penelitian & Konsultasi":
		*e = SubIndustryType_JasaPenelitianAmpersandKonsultasi
	case "Jasa Pengeboran Minyak & Gas":
		*e = SubIndustryType_JasaPengeboranMinyakAmpersandGas
	case "Jasa Pengelolaan Lingkungan & Sarana":
		*e = SubIndustryType_JasaPengelolaanLingkunganAmpersandSarana
	case "Jasa & Perlengkapan Minyak, Gas & Batu Bara":
		*e = SubIndustryType_JasaAmpersandPerlengkapanMinyakCommaGasAmpersandBatuBara
	case "Jasa Personalia":
		*e = SubIndustryType_JasaPersonalia
	case "Jasa Real Estat":
		*e = SubIndustryType_JasaRealEstat
	case "Jasa Telekomunikasi Kabel":
		*e = SubIndustryType_JasaTelekomunikasiKabel
	case "Jasa Telekomunikasi Nirkabel":
		*e = SubIndustryType_JasaTelekomunikasiNirkabel
	case "Jasa Telekomunikasi Terintegrasi":
		*e = SubIndustryType_JasaTelekomunikasiTerintegrasi
	case "Kayu":
		*e = SubIndustryType_Kayu
	case "Kertas":
		*e = SubIndustryType_Kertas
	case "Komponen & Peralatan Kelistrikan":
		*e = SubIndustryType_KomponenAmpersandPeralatanKelistrikan
	case "Konstruksi Bangunan":
		*e = SubIndustryType_KonstruksiBangunan
	case "Logam & Mineral Lainnya":
		*e = SubIndustryType_LogamAmpersandMineralLainnya
	case "Logistik & Pengantaran":
		*e = SubIndustryType_LogistikAmpersandPengantaran
	case "Makanan Olahan":
		*e = SubIndustryType_MakananOlahan
	case "Manajemen Investasi":
		*e = SubIndustryType_ManajemenInvestasi
	case "Maskapai Penerbangan":
		*e = SubIndustryType_MaskapaiPenerbangan
	case "Material Konstruksi":
		*e = SubIndustryType_MaterialKonstruksi
	case "Mesin & Komponen Perindustrian":
		*e = SubIndustryType_MesinAmpersandKomponenPerindustrian
	case "Mesin Konstruksi & Kendaraan Berat":
		*e = SubIndustryType_MesinKonstruksiAmpersandKendaraanBerat
	case "Minuman Keras":
		*e = SubIndustryType_MinumanKeras
	case "Minuman Ringan":
		*e = SubIndustryType_MinumanRingan
	case "Operator Bandar Udara":
		*e = SubIndustryType_OperatorBandarUdara
	case "Operator Jalan Tol & Rel":
		*e = SubIndustryType_OperatorJalanTolAmpersandRel
	case "Operator Pelabuhan":
		*e = SubIndustryType_OperatorPelabuhan
	case "Pakaian, Aksesoris, & Tas":
		*e = SubIndustryType_PakaianCommaAksesorisCommaAmpersandTas
	case "Pembiayaan Konsumen":
		*e = SubIndustryType_PembiayaanKonsumen
	case "Penerbitan":
		*e = SubIndustryType_Penerbitan
	case "Pengembang & Operator Real Estat":
		*e = SubIndustryType_PengembangAmpersandOperatorRealEstat
	case "Penyedia & Distribusi Perlengkapan Kesehatan":
		*e = SubIndustryType_PenyediaAmpersandDistribusiPerlengkapanKesehatan
	case "Penyedia Jasa Kesehatan":
		*e = SubIndustryType_PenyediaJasaKesehatan
	case "Penyiaran":
		*e = SubIndustryType_Penyiaran
	case "Penyiaran Berbayar":
		*e = SubIndustryType_PenyiaranBerbayar
	case "Penyimpanan & Distribusi Minyak & Gas":
		*e = SubIndustryType_PenyimpananAmpersandDistribusiMinyakAmpersandGas
	case "Peralatan Energi Alternatif":
		*e = SubIndustryType_PeralatanEnergiAlternatif
	case "Peralatan Jaringan":
		*e = SubIndustryType_PeralatanJaringan
	case "Peralatan Kantor":
		*e = SubIndustryType_PeralatanKantor
	case "Peralatan Olah Raga & Barang Hobi":
		*e = SubIndustryType_PeralatanOlahRagaAmpersandBarangHobi
	case "Peralatan Rumah Tangga":
		*e = SubIndustryType_PeralatanRumahTangga
	case "Perangkat & Instrumen Elektronik":
		*e = SubIndustryType_PerangkatAmpersandInstrumenElektronik
	case "Perangkat Komputer":
		*e = SubIndustryType_PerangkatKomputer
	case "Perangkat Lunak":
		*e = SubIndustryType_PerangkatLunak
	case "Percetakan Komersial":
		*e = SubIndustryType_PercetakanKomersial
	case "Perdagangan Aneka Barang Perindustrian":
		*e = SubIndustryType_PerdaganganAnekaBarangPerindustrian
	case "Periklanan":
		*e = SubIndustryType_Periklanan
	case "Perkebunan & Tanaman Pangan":
		*e = SubIndustryType_PerkebunanAmpersandTanamanPangan
	case "Perlengkapan Rumah Tangga":
		*e = SubIndustryType_PerlengkapanRumahTangga
	case "Perusahaan Holding Keuangan":
		*e = SubIndustryType_PerusahaanHoldingKeuangan
	case "Perusahaan Holding Multi-sektor":
		*e = SubIndustryType_PerusahaanHoldingMultiSektor
	case "Perusahaan Investasi":
		*e = SubIndustryType_PerusahaanInvestasi
	case "Produk Hutan Lainnya":
		*e = SubIndustryType_ProdukHutanLainnya
	case "Produk Perawatan Tubuh":
		*e = SubIndustryType_ProdukPerawatanTubuh
	case "Produk & Perlengkapan Bangunan":
		*e = SubIndustryType_ProdukAmpersandPerlengkapanBangunan
	case "Produksi Batu Bara":
		*e = SubIndustryType_ProduksiBatuBara
	case "Produksi & Penyulingan Minyak & Gas":
		*e = SubIndustryType_ProduksiAmpersandPenyulinganMinyakAmpersandGas
	case "Produk Susu Olahan":
		*e = SubIndustryType_ProdukSusuOlahan
	case "Produsen Furnitur Rumah":
		*e = SubIndustryType_ProdusenFurniturRumah
	case "Reasuransi":
		*e = SubIndustryType_Reasuransi
	case "Ritel Barang Rumah Tangga":
		*e = SubIndustryType_RitelBarangRumahTangga
	case "Ritel & Distributor Makanan":
		*e = SubIndustryType_RitelAmpersandDistributorMakanan
	case "Ritel & Distributor Obat-obatan":
		*e = SubIndustryType_RitelAmpersandDistributorObatObatan
	case "Ritel Elektronik":
		*e = SubIndustryType_RitelElektronik
	case "Ritel Otomotif":
		*e = SubIndustryType_RitelOtomotif
	case "Ritel Pakaian & Tekstil":
		*e = SubIndustryType_RitelPakaianAmpersandTekstil
	case "Rokok":
		*e = SubIndustryType_Rokok
	case "Rumah Makan":
		*e = SubIndustryType_RumahMakan
	case "Suku Cadang Otomotif":
		*e = SubIndustryType_SukuCadangOtomotif
	case "Supermarket":
		*e = SubIndustryType_Supermarket
	case "Tekstil":
		*e = SubIndustryType_Tekstil
	case "Tembaga":
		*e = SubIndustryType_Tembaga
	case "Transportasi Jalanan":
		*e = SubIndustryType_TransportasiJalanan
	case "Utilitas Gas":
		*e = SubIndustryType_UtilitasGas
	case "Utilitas Listrik":
		*e = SubIndustryType_UtilitasListrik
	case "Wadah & Kemasan":
		*e = SubIndustryType_WadahAmpersandKemasan
	case "Others":
		*e = SubIndustryType_Others
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for SubIndustryType enum")
	}

	return nil
}

func (e SubIndustryType) String() string {
	return string(e)
}
