//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type SubSectorType string

const (
	SubSectorType_Asuransi                                  SubSectorType = "Asuransi"
	SubSectorType_Bank                                      SubSectorType = "Bank"
	SubSectorType_BarangBaku                                SubSectorType = "Barang Baku"
	SubSectorType_BarangPerindustrian                       SubSectorType = "Barang Perindustrian"
	SubSectorType_BarangRekreasi                            SubSectorType = "Barang Rekreasi"
	SubSectorType_BarangRumahTangga                         SubSectorType = "Barang Rumah Tangga"
	SubSectorType_EnergiAlternatif                          SubSectorType = "Energi Alternatif"
	SubSectorType_FarmasiAmpersandRisetKesehatan            SubSectorType = "Farmasi & Riset Kesehatan"
	SubSectorType_InfrastrukturTransportasi                 SubSectorType = "Infrastruktur Transportasi"
	SubSectorType_JasaInvestasi                             SubSectorType = "Jasa Investasi"
	SubSectorType_JasaKonsumen                              SubSectorType = "Jasa Konsumen"
	SubSectorType_JasaPembiayaan                            SubSectorType = "Jasa Pembiayaan"
	SubSectorType_JasaAmpersandPeralatanKesehatan           SubSectorType = "Jasa & Peralatan Kesehatan"
	SubSectorType_JasaPerindustrian                         SubSectorType = "Jasa Perindustrian"
	SubSectorType_KonstruksiBangunan                        SubSectorType = "Konstruksi Bangunan"
	SubSectorType_LogistikAmpersandPengantaran              SubSectorType = "Logistik & Pengantaran"
	SubSectorType_MakananAmpersandMinuman                   SubSectorType = "Makanan & Minuman"
	SubSectorType_MediaAmpersandHiburan                     SubSectorType = "Media & Hiburan"
	SubSectorType_MinyakCommaGasAmpersandBatuBara           SubSectorType = "Minyak, Gas & Batu Bara"
	SubSectorType_OtomotifAmpersandKomponenOtomotif         SubSectorType = "Otomotif & Komponen Otomotif"
	SubSectorType_PakaianAmpersandBarangMewah               SubSectorType = "Pakaian & Barang Mewah"
	SubSectorType_PerangkatKerasAmpersandPeralatanTeknologi SubSectorType = "Perangkat Keras & Peralatan Teknologi"
	SubSectorType_PerangkatLunakAmpersandJasaTi             SubSectorType = "Perangkat Lunak & Jasa TI"
	SubSectorType_PerdaganganRitel                          SubSectorType = "Perdagangan Ritel"
	SubSectorType_PerdaganganRitelBarangPrimer              SubSectorType = "Perdagangan Ritel Barang Primer"
	SubSectorType_PerusahaanHoldingAmpersandInvestasi       SubSectorType = "Perusahaan Holding & Investasi"
	SubSectorType_PerusahaanHoldingMultiSektor              SubSectorType = "Perusahaan Holding Multi Sektor"
	SubSectorType_ProdukRumahTanggaTidakTahanLama           SubSectorType = "Produk Rumah Tangga Tidak Tahan Lama"
	SubSectorType_PropertiAmpersandRealEstat                SubSectorType = "Properti & Real Estat"
	SubSectorType_Rokok                                     SubSectorType = "Rokok"
	SubSectorType_Telekomunikasi                            SubSectorType = "Telekomunikasi"
	SubSectorType_Transportasi                              SubSectorType = "Transportasi"
	SubSectorType_Utilitas                                  SubSectorType = "Utilitas"
	SubSectorType_Others                                    SubSectorType = "Others"
)

var SubSectorTypeAllValues = []SubSectorType{
	SubSectorType_Asuransi,
	SubSectorType_Bank,
	SubSectorType_BarangBaku,
	SubSectorType_BarangPerindustrian,
	SubSectorType_BarangRekreasi,
	SubSectorType_BarangRumahTangga,
	SubSectorType_EnergiAlternatif,
	SubSectorType_FarmasiAmpersandRisetKesehatan,
	SubSectorType_InfrastrukturTransportasi,
	SubSectorType_JasaInvestasi,
	SubSectorType_JasaKonsumen,
	SubSectorType_JasaPembiayaan,
	SubSectorType_JasaAmpersandPeralatanKesehatan,
	SubSectorType_JasaPerindustrian,
	SubSectorType_KonstruksiBangunan,
	SubSectorType_LogistikAmpersandPengantaran,
	SubSectorType_MakananAmpersandMinuman,
	SubSectorType_MediaAmpersandHiburan,
	SubSectorType_MinyakCommaGasAmpersandBatuBara,
	SubSectorType_OtomotifAmpersandKomponenOtomotif,
	SubSectorType_PakaianAmpersandBarangMewah,
	SubSectorType_PerangkatKerasAmpersandPeralatanTeknologi,
	SubSectorType_PerangkatLunakAmpersandJasaTi,
	SubSectorType_PerdaganganRitel,
	SubSectorType_PerdaganganRitelBarangPrimer,
	SubSectorType_PerusahaanHoldingAmpersandInvestasi,
	SubSectorType_PerusahaanHoldingMultiSektor,
	SubSectorType_ProdukRumahTanggaTidakTahanLama,
	SubSectorType_PropertiAmpersandRealEstat,
	SubSectorType_Rokok,
	SubSectorType_Telekomunikasi,
	SubSectorType_Transportasi,
	SubSectorType_Utilitas,
	SubSectorType_Others,
}

func (e *SubSectorType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Asuransi":
		*e = SubSectorType_Asuransi
	case "Bank":
		*e = SubSectorType_Bank
	case "Barang Baku":
		*e = SubSectorType_BarangBaku
	case "Barang Perindustrian":
		*e = SubSectorType_BarangPerindustrian
	case "Barang Rekreasi":
		*e = SubSectorType_BarangRekreasi
	case "Barang Rumah Tangga":
		*e = SubSectorType_BarangRumahTangga
	case "Energi Alternatif":
		*e = SubSectorType_EnergiAlternatif
	case "Farmasi & Riset Kesehatan":
		*e = SubSectorType_FarmasiAmpersandRisetKesehatan
	case "Infrastruktur Transportasi":
		*e = SubSectorType_InfrastrukturTransportasi
	case "Jasa Investasi":
		*e = SubSectorType_JasaInvestasi
	case "Jasa Konsumen":
		*e = SubSectorType_JasaKonsumen
	case "Jasa Pembiayaan":
		*e = SubSectorType_JasaPembiayaan
	case "Jasa & Peralatan Kesehatan":
		*e = SubSectorType_JasaAmpersandPeralatanKesehatan
	case "Jasa Perindustrian":
		*e = SubSectorType_JasaPerindustrian
	case "Konstruksi Bangunan":
		*e = SubSectorType_KonstruksiBangunan
	case "Logistik & Pengantaran":
		*e = SubSectorType_LogistikAmpersandPengantaran
	case "Makanan & Minuman":
		*e = SubSectorType_MakananAmpersandMinuman
	case "Media & Hiburan":
		*e = SubSectorType_MediaAmpersandHiburan
	case "Minyak, Gas & Batu Bara":
		*e = SubSectorType_MinyakCommaGasAmpersandBatuBara
	case "Otomotif & Komponen Otomotif":
		*e = SubSectorType_OtomotifAmpersandKomponenOtomotif
	case "Pakaian & Barang Mewah":
		*e = SubSectorType_PakaianAmpersandBarangMewah
	case "Perangkat Keras & Peralatan Teknologi":
		*e = SubSectorType_PerangkatKerasAmpersandPeralatanTeknologi
	case "Perangkat Lunak & Jasa TI":
		*e = SubSectorType_PerangkatLunakAmpersandJasaTi
	case "Perdagangan Ritel":
		*e = SubSectorType_PerdaganganRitel
	case "Perdagangan Ritel Barang Primer":
		*e = SubSectorType_PerdaganganRitelBarangPrimer
	case "Perusahaan Holding & Investasi":
		*e = SubSectorType_PerusahaanHoldingAmpersandInvestasi
	case "Perusahaan Holding Multi Sektor":
		*e = SubSectorType_PerusahaanHoldingMultiSektor
	case "Produk Rumah Tangga Tidak Tahan Lama":
		*e = SubSectorType_ProdukRumahTanggaTidakTahanLama
	case "Properti & Real Estat":
		*e = SubSectorType_PropertiAmpersandRealEstat
	case "Rokok":
		*e = SubSectorType_Rokok
	case "Telekomunikasi":
		*e = SubSectorType_Telekomunikasi
	case "Transportasi":
		*e = SubSectorType_Transportasi
	case "Utilitas":
		*e = SubSectorType_Utilitas
	case "Others":
		*e = SubSectorType_Others
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for SubSectorType enum")
	}

	return nil
}

func (e SubSectorType) String() string {
	return string(e)
}
