CREATE TYPE sector_type AS ENUM (
    'Barang Baku',
    'Barang Konsumen Non-Primer',
    'Barang Konsumen Primer',
    'Energi',
    'Infrastruktur',
    'Kesehatan',
    'Keuangan',
    'Perindustrian',
    'Properti & Real Estat',
    'Teknologi',
    'Transportasi & Logistik',
    'Others'
);

CREATE TYPE sub_sector_type AS ENUM (
    'Asuransi',
    'Bank',
    'Barang Baku',
    'Barang Perindustrian',
    'Barang Rekreasi',
    'Barang Rumah Tangga',
    'Energi Alternatif',
    'Farmasi & Riset Kesehatan',
    'Infrastruktur Transportasi',
    'Jasa Investasi',
    'Jasa Konsumen',
    'Jasa Pembiayaan',
    'Jasa & Peralatan Kesehatan',
    'Jasa Perindustrian',
    'Konstruksi Bangunan',
    'Logistik & Pengantaran',
    'Makanan & Minuman',
    'Media & Hiburan',
    'Minyak, Gas & Batu Bara',
    'Otomotif & Komponen Otomotif',
    'Pakaian & Barang Mewah',
    'Perangkat Keras & Peralatan Teknologi',
    'Perangkat Lunak & Jasa TI',
    'Perdagangan Ritel',
    'Perdagangan Ritel Barang Primer',
    'Perusahaan Holding & Investasi',
    'Perusahaan Holding Multi Sektor',
    'Produk Rumah Tangga Tidak Tahan Lama',
    'Properti & Real Estat',
    'Rokok',
    'Telekomunikasi',
    'Transportasi',
    'Utilitas',
    'Others'
);

CREATE TYPE industry_type AS ENUM (
    'Aplikasi & Jasa Internet',
    'Asuransi',
    'Bank',
    'Barang Elektronik Konsumen',
    'Barang Kimia',
    'Barang Rumah Tangga',
    'Batu Bara',
    'Department Store',
    'Distributor Barang Konsumen',
    'Farmasi',
    'Hiburan & Film',
    'Jasa Investasi',
    'Jasa Komersial',
    'Jasa & Konsultan TI',
    'Jasa Profesional',
    'Jasa Telekomunikasi',
    'Jasa Telekomunikasi Nirkabel',
    'Kelistrikan',
    'Komponen Otomotif',
    'Konstruksi Bangunan',
    'Logam & Mineral',
    'Logistik & Pengantaran',
    'Makanan Olahan',
    'Maskapai Penerbangan',
    'Material Konstruksi',
    'Media',
    'Mesin',
    'Minuman',
    'Minyak & Gas',
    'Operator Infrastruktur Transportasi',
    'Pakaian & Barang Mewah',
    'Pariwisata & Rekreasi',
    'Pembiayaan Konsumen',
    'Pendidikan & Jasa Penunjang',
    'Pendukung Minyak, Gas & Batu Bara',
    'Pengangkutan Darat Penumpang',
    'Pengelola & Pengembang Real Estat',
    'Penyedia Jasa Kesehatan',
    'Peralatan Energi Alternatif',
    'Peralatan Jaringan',
    'Peralatan Olah Raga & Barang Hobi',
    'Peralatan & Perlengkapan Kesehatan',
    'Perangkat, Instrumen & Komponen Elektronik',
    'Perangkat Komputer',
    'Perangkat Lunak',
    'Perdagangan Aneka Barang Perindustrian',
    'Perdagangan Ritel Barang Primer',
    'Perhutanan & Kertas',
    'Perusahaan Holding & Investasi',
    'Perusahaan Holding Multi-sektor',
    'Produk Makanan Pertanian',
    'Produk Perawatan Tubuh',
    'Produk & Perlengkapan Bangunan',
    'Ritel Khusus',
    'Rokok',
    'Utilitas Gas',
    'Utilitas Listrik',
    'Wadah & Kemasan',
    'Others'
);

CREATE TYPE sub_industry_type AS ENUM (
    'Agen Perjalanan',
    'Alas Kaki',
    'Alumunium',
    'Aplikasi & Jasa Internet',
    'Asuransi Jiwa',
    'Asuransi Umum',
    'Baja & Besi',
    'Ban',
    'Bank',
    'Bank Investasi & Perantara Perdagangan',
    'Barang Elektronik Konsumen',
    'Barang Kimia Dasar',
    'Barang Kimia Khusus',
    'Barang Kimia Pertanian',
    'Department Store',
    'Distribusi Batu Bara',
    'Distributor Barang Konsumen',
    'Emas',
    'Farmasi',
    'Fasilitas Rekreasi & Olah Raga',
    'Hiburan & Film',
    'Hotel, Resor & Kapal Pesiar',
    'Ikan, Daging & Produk Unggas',
    'Jasa & Konsultan TI',
    'Jasa Pendidikan',
    'Jasa Pendukung Bisnis',
    'Jasa Penelitian & Konsultasi',
    'Jasa Pengeboran Minyak & Gas',
    'Jasa Pengelolaan Lingkungan & Sarana',
    'Jasa & Perlengkapan Minyak, Gas & Batu Bara',
    'Jasa Personalia',
    'Jasa Real Estat',
    'Jasa Telekomunikasi Kabel',
    'Jasa Telekomunikasi Nirkabel',
    'Jasa Telekomunikasi Terintegrasi',
    'Kayu',
    'Kertas',
    'Komponen & Peralatan Kelistrikan',
    'Konstruksi Bangunan',
    'Logam & Mineral Lainnya',
    'Logistik & Pengantaran',
    'Makanan Olahan',
    'Manajemen Investasi',
    'Maskapai Penerbangan',
    'Material Konstruksi',
    'Mesin & Komponen Perindustrian',
    'Mesin Konstruksi & Kendaraan Berat',
    'Minuman Keras',
    'Minuman Ringan',
    'Operator Bandar Udara',
    'Operator Jalan Tol & Rel',
    'Operator Pelabuhan',
    'Pakaian, Aksesoris, & Tas',
    'Pembiayaan Konsumen',
    'Penerbitan',
    'Pengembang & Operator Real Estat',
    'Penyedia & Distribusi Perlengkapan Kesehatan',
    'Penyedia Jasa Kesehatan',
    'Penyiaran',
    'Penyiaran Berbayar',
    'Penyimpanan & Distribusi Minyak & Gas',
    'Peralatan Energi Alternatif',
    'Peralatan Jaringan',
    'Peralatan Kantor',
    'Peralatan Olah Raga & Barang Hobi',
    'Peralatan Rumah Tangga',
    'Perangkat & Instrumen Elektronik',
    'Perangkat Komputer',
    'Perangkat Lunak',
    'Percetakan Komersial',
    'Perdagangan Aneka Barang Perindustrian',
    'Periklanan',
    'Perkebunan & Tanaman Pangan',
    'Perlengkapan Rumah Tangga',
    'Perusahaan Holding Keuangan',
    'Perusahaan Holding Multi-sektor',
    'Perusahaan Investasi',
    'Produk Hutan Lainnya',
    'Produk Perawatan Tubuh',
    'Produk & Perlengkapan Bangunan',
    'Produksi Batu Bara',
    'Produksi & Penyulingan Minyak & Gas',
    'Produk Susu Olahan',
    'Produsen Furnitur Rumah',
    'Reasuransi',
    'Ritel Barang Rumah Tangga',
    'Ritel & Distributor Makanan',
    'Ritel & Distributor Obat-obatan',
    'Ritel Elektronik',
    'Ritel Otomotif',
    'Ritel Pakaian & Tekstil',
    'Rokok',
    'Rumah Makan',
    'Suku Cadang Otomotif',
    'Supermarket',
    'Tekstil',
    'Tembaga',
    'Transportasi Jalanan',
    'Utilitas Gas',
    'Utilitas Listrik',
    'Wadah & Kemasan',
    'Others'
);

CREATE TABLE IF NOT EXISTS companies (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    sector sector_type NOT NULL DEFAULT 'Others',
    sub_sector sub_sector_type NOT NULL DEFAULT 'Others',
    industry industry_type NOT NULL DEFAULT 'Others',
    sub_industry sub_industry_type NOT NULL DEFAULT 'Others',
    ticker text NOT NULL
);
