//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type MarketDetectorSummaries struct {
	TotalValue    float64
	ID            uuid.UUID `sql:"primary_key"`
	Symbol        string
	AccdistStatus string
	TradeDate     time.Time
	CreatedAt     time.Time
}
