//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Attachments = newAttachmentsTable("public", "attachments", "")

type attachmentsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	IdxAnnouncementID postgres.ColumnString
	OriginalFilename  postgres.ColumnString
	Checksum          postgres.ColumnString
	StoragePath       postgres.ColumnString
	UploadedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AttachmentsTable struct {
	attachmentsTable

	EXCLUDED attachmentsTable
}

// AS creates new AttachmentsTable with assigned alias
func (a AttachmentsTable) AS(alias string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AttachmentsTable with assigned schema name
func (a AttachmentsTable) FromSchema(schemaName string) *AttachmentsTable {
	return newAttachmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AttachmentsTable with assigned table prefix
func (a AttachmentsTable) WithPrefix(prefix string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AttachmentsTable with assigned table suffix
func (a AttachmentsTable) WithSuffix(suffix string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAttachmentsTable(schemaName, tableName, alias string) *AttachmentsTable {
	return &AttachmentsTable{
		attachmentsTable: newAttachmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newAttachmentsTableImpl("", "excluded", ""),
	}
}

func newAttachmentsTableImpl(schemaName, tableName, alias string) attachmentsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		IdxAnnouncementIDColumn = postgres.StringColumn("idx_announcement_id")
		OriginalFilenameColumn  = postgres.StringColumn("original_filename")
		ChecksumColumn          = postgres.StringColumn("checksum")
		StoragePathColumn       = postgres.StringColumn("storage_path")
		UploadedAtColumn        = postgres.TimestampzColumn("uploaded_at")
		allColumns              = postgres.ColumnList{IDColumn, IdxAnnouncementIDColumn, OriginalFilenameColumn, ChecksumColumn, StoragePathColumn, UploadedAtColumn}
		mutableColumns          = postgres.ColumnList{IdxAnnouncementIDColumn, OriginalFilenameColumn, ChecksumColumn, StoragePathColumn, UploadedAtColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, UploadedAtColumn}
	)

	return attachmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		IdxAnnouncementID: IdxAnnouncementIDColumn,
		OriginalFilename:  OriginalFilenameColumn,
		Checksum:          ChecksumColumn,
		StoragePath:       StoragePathColumn,
		UploadedAt:        UploadedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
