//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Attachments = newAttachmentsTable("public", "attachments", "")

type attachmentsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	IdxAnnouncementID postgres.ColumnString
	IdxURL            postgres.ColumnString
	Error             postgres.ColumnString
	OriginalFilename  postgres.ColumnString
	Filename          postgres.ColumnString
	Checksum          postgres.ColumnString
	StoragePath       postgres.ColumnString
	Title             postgres.ColumnString
	StockCode         postgres.ColumnString
	IsDownloaded      postgres.ColumnBool
	IsProcessing      postgres.ColumnBool
	Date              postgres.ColumnTimestampz
	UploadedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AttachmentsTable struct {
	attachmentsTable

	EXCLUDED attachmentsTable
}

// AS creates new AttachmentsTable with assigned alias
func (a AttachmentsTable) AS(alias string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AttachmentsTable with assigned schema name
func (a AttachmentsTable) FromSchema(schemaName string) *AttachmentsTable {
	return newAttachmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AttachmentsTable with assigned table prefix
func (a AttachmentsTable) WithPrefix(prefix string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AttachmentsTable with assigned table suffix
func (a AttachmentsTable) WithSuffix(suffix string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAttachmentsTable(schemaName, tableName, alias string) *AttachmentsTable {
	return &AttachmentsTable{
		attachmentsTable: newAttachmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newAttachmentsTableImpl("", "excluded", ""),
	}
}

func newAttachmentsTableImpl(schemaName, tableName, alias string) attachmentsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		IdxAnnouncementIDColumn = postgres.StringColumn("idx_announcement_id")
		IdxURLColumn            = postgres.StringColumn("idx_url")
		ErrorColumn             = postgres.StringColumn("error")
		OriginalFilenameColumn  = postgres.StringColumn("original_filename")
		FilenameColumn          = postgres.StringColumn("filename")
		ChecksumColumn          = postgres.StringColumn("checksum")
		StoragePathColumn       = postgres.StringColumn("storage_path")
		TitleColumn             = postgres.StringColumn("title")
		StockCodeColumn         = postgres.StringColumn("stock_code")
		IsDownloadedColumn      = postgres.BoolColumn("is_downloaded")
		IsProcessingColumn      = postgres.BoolColumn("is_processing")
		DateColumn              = postgres.TimestampzColumn("date")
		UploadedAtColumn        = postgres.TimestampzColumn("uploaded_at")
		allColumns              = postgres.ColumnList{IDColumn, IdxAnnouncementIDColumn, IdxURLColumn, ErrorColumn, OriginalFilenameColumn, FilenameColumn, ChecksumColumn, StoragePathColumn, TitleColumn, StockCodeColumn, IsDownloadedColumn, IsProcessingColumn, DateColumn, UploadedAtColumn}
		mutableColumns          = postgres.ColumnList{IdxAnnouncementIDColumn, IdxURLColumn, ErrorColumn, OriginalFilenameColumn, FilenameColumn, ChecksumColumn, StoragePathColumn, TitleColumn, StockCodeColumn, IsDownloadedColumn, IsProcessingColumn, DateColumn, UploadedAtColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, IsProcessingColumn, UploadedAtColumn}
	)

	return attachmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		IdxAnnouncementID: IdxAnnouncementIDColumn,
		IdxURL:            IdxURLColumn,
		Error:             ErrorColumn,
		OriginalFilename:  OriginalFilenameColumn,
		Filename:          FilenameColumn,
		Checksum:          ChecksumColumn,
		StoragePath:       StoragePathColumn,
		Title:             TitleColumn,
		StockCode:         StockCodeColumn,
		IsDownloaded:      IsDownloadedColumn,
		IsProcessing:      IsProcessingColumn,
		Date:              DateColumn,
		UploadedAt:        UploadedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
