//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BrokerTransactions = newBrokerTransactionsTable("public", "broker_transactions", "")

type brokerTransactionsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	SummaryID    postgres.ColumnString
	Symbol       postgres.ColumnString
	InvestorType postgres.ColumnString
	Side         postgres.ColumnString
	BrokerCode   postgres.ColumnString
	Frequency    postgres.ColumnInteger
	Lots         postgres.ColumnInteger
	AvgPrice     postgres.ColumnFloat
	TradeDate    postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BrokerTransactionsTable struct {
	brokerTransactionsTable

	EXCLUDED brokerTransactionsTable
}

// AS creates new BrokerTransactionsTable with assigned alias
func (a BrokerTransactionsTable) AS(alias string) *BrokerTransactionsTable {
	return newBrokerTransactionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BrokerTransactionsTable with assigned schema name
func (a BrokerTransactionsTable) FromSchema(schemaName string) *BrokerTransactionsTable {
	return newBrokerTransactionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BrokerTransactionsTable with assigned table prefix
func (a BrokerTransactionsTable) WithPrefix(prefix string) *BrokerTransactionsTable {
	return newBrokerTransactionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BrokerTransactionsTable with assigned table suffix
func (a BrokerTransactionsTable) WithSuffix(suffix string) *BrokerTransactionsTable {
	return newBrokerTransactionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBrokerTransactionsTable(schemaName, tableName, alias string) *BrokerTransactionsTable {
	return &BrokerTransactionsTable{
		brokerTransactionsTable: newBrokerTransactionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newBrokerTransactionsTableImpl("", "excluded", ""),
	}
}

func newBrokerTransactionsTableImpl(schemaName, tableName, alias string) brokerTransactionsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		SummaryIDColumn    = postgres.StringColumn("summary_id")
		SymbolColumn       = postgres.StringColumn("symbol")
		InvestorTypeColumn = postgres.StringColumn("investor_type")
		SideColumn         = postgres.StringColumn("side")
		BrokerCodeColumn   = postgres.StringColumn("broker_code")
		FrequencyColumn    = postgres.IntegerColumn("frequency")
		LotsColumn         = postgres.IntegerColumn("lots")
		AvgPriceColumn     = postgres.FloatColumn("avg_price")
		TradeDateColumn    = postgres.DateColumn("trade_date")
		allColumns         = postgres.ColumnList{IDColumn, SummaryIDColumn, SymbolColumn, InvestorTypeColumn, SideColumn, BrokerCodeColumn, FrequencyColumn, LotsColumn, AvgPriceColumn, TradeDateColumn}
		mutableColumns     = postgres.ColumnList{SummaryIDColumn, SymbolColumn, InvestorTypeColumn, SideColumn, BrokerCodeColumn, FrequencyColumn, LotsColumn, AvgPriceColumn, TradeDateColumn}
		defaultColumns     = postgres.ColumnList{IDColumn}
	)

	return brokerTransactionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		SummaryID:    SummaryIDColumn,
		Symbol:       SymbolColumn,
		InvestorType: InvestorTypeColumn,
		Side:         SideColumn,
		BrokerCode:   BrokerCodeColumn,
		Frequency:    FrequencyColumn,
		Lots:         LotsColumn,
		AvgPrice:     AvgPriceColumn,
		TradeDate:    TradeDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
