//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ExtractedAttachments = newExtractedAttachmentsTable("public", "extracted_attachments", "")

type extractedAttachmentsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	AttachmentID      postgres.ColumnString
	IdxAnnouncementID postgres.ColumnString
	Title             postgres.ColumnString
	StockCode         postgres.ColumnString
	ExtractedAt       postgres.ColumnTimestampz
	MinioKey          postgres.ColumnString
	Metadata          postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ExtractedAttachmentsTable struct {
	extractedAttachmentsTable

	EXCLUDED extractedAttachmentsTable
}

// AS creates new ExtractedAttachmentsTable with assigned alias
func (a ExtractedAttachmentsTable) AS(alias string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ExtractedAttachmentsTable with assigned schema name
func (a ExtractedAttachmentsTable) FromSchema(schemaName string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ExtractedAttachmentsTable with assigned table prefix
func (a ExtractedAttachmentsTable) WithPrefix(prefix string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ExtractedAttachmentsTable with assigned table suffix
func (a ExtractedAttachmentsTable) WithSuffix(suffix string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newExtractedAttachmentsTable(schemaName, tableName, alias string) *ExtractedAttachmentsTable {
	return &ExtractedAttachmentsTable{
		extractedAttachmentsTable: newExtractedAttachmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newExtractedAttachmentsTableImpl("", "excluded", ""),
	}
}

func newExtractedAttachmentsTableImpl(schemaName, tableName, alias string) extractedAttachmentsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		AttachmentIDColumn      = postgres.StringColumn("attachment_id")
		IdxAnnouncementIDColumn = postgres.StringColumn("idx_announcement_id")
		TitleColumn             = postgres.StringColumn("title")
		StockCodeColumn         = postgres.StringColumn("stock_code")
		ExtractedAtColumn       = postgres.TimestampzColumn("extracted_at")
		MinioKeyColumn          = postgres.StringColumn("minio_key")
		MetadataColumn          = postgres.StringColumn("metadata")
		allColumns              = postgres.ColumnList{IDColumn, AttachmentIDColumn, IdxAnnouncementIDColumn, TitleColumn, StockCodeColumn, ExtractedAtColumn, MinioKeyColumn, MetadataColumn}
		mutableColumns          = postgres.ColumnList{AttachmentIDColumn, IdxAnnouncementIDColumn, TitleColumn, StockCodeColumn, ExtractedAtColumn, MinioKeyColumn, MetadataColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, ExtractedAtColumn, MetadataColumn}
	)

	return extractedAttachmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		AttachmentID:      AttachmentIDColumn,
		IdxAnnouncementID: IdxAnnouncementIDColumn,
		Title:             TitleColumn,
		StockCode:         StockCodeColumn,
		ExtractedAt:       ExtractedAtColumn,
		MinioKey:          MinioKeyColumn,
		Metadata:          MetadataColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
