//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MarketDetectorSummaries = newMarketDetectorSummariesTable("public", "market_detector_summaries", "")

type marketDetectorSummariesTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	Symbol        postgres.ColumnString
	AccdistStatus postgres.ColumnString
	TotalValue    postgres.ColumnFloat
	CreatedAt     postgres.ColumnTimestampz
	TradeDate     postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MarketDetectorSummariesTable struct {
	marketDetectorSummariesTable

	EXCLUDED marketDetectorSummariesTable
}

// AS creates new MarketDetectorSummariesTable with assigned alias
func (a MarketDetectorSummariesTable) AS(alias string) *MarketDetectorSummariesTable {
	return newMarketDetectorSummariesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MarketDetectorSummariesTable with assigned schema name
func (a MarketDetectorSummariesTable) FromSchema(schemaName string) *MarketDetectorSummariesTable {
	return newMarketDetectorSummariesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MarketDetectorSummariesTable with assigned table prefix
func (a MarketDetectorSummariesTable) WithPrefix(prefix string) *MarketDetectorSummariesTable {
	return newMarketDetectorSummariesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MarketDetectorSummariesTable with assigned table suffix
func (a MarketDetectorSummariesTable) WithSuffix(suffix string) *MarketDetectorSummariesTable {
	return newMarketDetectorSummariesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMarketDetectorSummariesTable(schemaName, tableName, alias string) *MarketDetectorSummariesTable {
	return &MarketDetectorSummariesTable{
		marketDetectorSummariesTable: newMarketDetectorSummariesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newMarketDetectorSummariesTableImpl("", "excluded", ""),
	}
}

func newMarketDetectorSummariesTableImpl(schemaName, tableName, alias string) marketDetectorSummariesTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		SymbolColumn        = postgres.StringColumn("symbol")
		AccdistStatusColumn = postgres.StringColumn("accdist_status")
		TotalValueColumn    = postgres.FloatColumn("total_value")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		TradeDateColumn     = postgres.DateColumn("trade_date")
		allColumns          = postgres.ColumnList{IDColumn, SymbolColumn, AccdistStatusColumn, TotalValueColumn, CreatedAtColumn, TradeDateColumn}
		mutableColumns      = postgres.ColumnList{SymbolColumn, AccdistStatusColumn, TotalValueColumn, CreatedAtColumn, TradeDateColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return marketDetectorSummariesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Symbol:        SymbolColumn,
		AccdistStatus: AccdistStatusColumn,
		TotalValue:    TotalValueColumn,
		CreatedAt:     CreatedAtColumn,
		TradeDate:     TradeDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
