// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package blobstorage

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreateBucket provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateBucket(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_CreateBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucket'
type MockStorage_CreateBucket_Call struct {
	*mock.Call
}

// CreateBucket is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) CreateBucket(ctx interface{}) *MockStorage_CreateBucket_Call {
	return &MockStorage_CreateBucket_Call{Call: _e.mock.On("CreateBucket", ctx)}
}

func (_c *MockStorage_CreateBucket_Call) Run(run func(ctx context.Context)) *MockStorage_CreateBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_CreateBucket_Call) Return(err error) *MockStorage_CreateBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_CreateBucket_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorage_CreateBucket_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type MockStorage
func (_mock *MockStorage) Download(ctx context.Context, object string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, object)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - object string
func (_e *MockStorage_Expecter) Download(ctx interface{}, object interface{}) *MockStorage_Download_Call {
	return &MockStorage_Download_Call{Call: _e.mock.On("Download", ctx, object)}
}

func (_c *MockStorage_Download_Call) Run(run func(ctx context.Context, object string)) *MockStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Download_Call) Return(readCloser io.ReadCloser, err error) *MockStorage_Download_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockStorage_Download_Call) RunAndReturn(run func(ctx context.Context, object string) (io.ReadCloser, error)) *MockStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockStorage
func (_mock *MockStorage) Exists(ctx context.Context, object string) (bool, error) {
	ret := _mock.Called(ctx, object)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, object)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, object)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, object)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - object string
func (_e *MockStorage_Expecter) Exists(ctx interface{}, object interface{}) *MockStorage_Exists_Call {
	return &MockStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, object)}
}

func (_c *MockStorage_Exists_Call) Run(run func(ctx context.Context, object string)) *MockStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Exists_Call) Return(b bool, err error) *MockStorage_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorage_Exists_Call) RunAndReturn(run func(ctx context.Context, object string) (bool, error)) *MockStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// SaveReader provides a mock function for the type MockStorage
func (_mock *MockStorage) SaveReader(ctx context.Context, filename string, content io.Reader, contentSize int64, contentType string) (SaveResult, error) {
	ret := _mock.Called(ctx, filename, content, contentSize, contentType)

	if len(ret) == 0 {
		panic("no return value specified for SaveReader")
	}

	var r0 SaveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) (SaveResult, error)); ok {
		return returnFunc(ctx, filename, content, contentSize, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) SaveResult); ok {
		r0 = returnFunc(ctx, filename, content, contentSize, contentType)
	} else {
		r0 = ret.Get(0).(SaveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r1 = returnFunc(ctx, filename, content, contentSize, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_SaveReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveReader'
type MockStorage_SaveReader_Call struct {
	*mock.Call
}

// SaveReader is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
//   - content io.Reader
//   - contentSize int64
//   - contentType string
func (_e *MockStorage_Expecter) SaveReader(ctx interface{}, filename interface{}, content interface{}, contentSize interface{}, contentType interface{}) *MockStorage_SaveReader_Call {
	return &MockStorage_SaveReader_Call{Call: _e.mock.On("SaveReader", ctx, filename, content, contentSize, contentType)}
}

func (_c *MockStorage_SaveReader_Call) Run(run func(ctx context.Context, filename string, content io.Reader, contentSize int64, contentType string)) *MockStorage_SaveReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorage_SaveReader_Call) Return(saveResult SaveResult, err error) *MockStorage_SaveReader_Call {
	_c.Call.Return(saveResult, err)
	return _c
}

func (_c *MockStorage_SaveReader_Call) RunAndReturn(run func(ctx context.Context, filename string, content io.Reader, contentSize int64, contentType string) (SaveResult, error)) *MockStorage_SaveReader_Call {
	_c.Call.Return(run)
	return _c
}
