//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AnalyzedCompanies = newAnalyzedCompaniesTable("public", "analyzed_companies", "")

type analyzedCompaniesTable struct {
	postgres.Table

	// Columns
	ID                    postgres.ColumnString
	CompanyID             postgres.ColumnString
	ExtractedAttachmentID postgres.ColumnString
	Path                  postgres.ColumnString
	CreatedAt             postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AnalyzedCompaniesTable struct {
	analyzedCompaniesTable

	EXCLUDED analyzedCompaniesTable
}

// AS creates new AnalyzedCompaniesTable with assigned alias
func (a AnalyzedCompaniesTable) AS(alias string) *AnalyzedCompaniesTable {
	return newAnalyzedCompaniesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AnalyzedCompaniesTable with assigned schema name
func (a AnalyzedCompaniesTable) FromSchema(schemaName string) *AnalyzedCompaniesTable {
	return newAnalyzedCompaniesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AnalyzedCompaniesTable with assigned table prefix
func (a AnalyzedCompaniesTable) WithPrefix(prefix string) *AnalyzedCompaniesTable {
	return newAnalyzedCompaniesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AnalyzedCompaniesTable with assigned table suffix
func (a AnalyzedCompaniesTable) WithSuffix(suffix string) *AnalyzedCompaniesTable {
	return newAnalyzedCompaniesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAnalyzedCompaniesTable(schemaName, tableName, alias string) *AnalyzedCompaniesTable {
	return &AnalyzedCompaniesTable{
		analyzedCompaniesTable: newAnalyzedCompaniesTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newAnalyzedCompaniesTableImpl("", "excluded", ""),
	}
}

func newAnalyzedCompaniesTableImpl(schemaName, tableName, alias string) analyzedCompaniesTable {
	var (
		IDColumn                    = postgres.StringColumn("id")
		CompanyIDColumn             = postgres.StringColumn("company_id")
		ExtractedAttachmentIDColumn = postgres.StringColumn("extracted_attachment_id")
		PathColumn                  = postgres.StringColumn("path")
		CreatedAtColumn             = postgres.TimestampzColumn("created_at")
		allColumns                  = postgres.ColumnList{IDColumn, CompanyIDColumn, ExtractedAttachmentIDColumn, PathColumn, CreatedAtColumn}
		mutableColumns              = postgres.ColumnList{CompanyIDColumn, ExtractedAttachmentIDColumn, PathColumn, CreatedAtColumn}
		defaultColumns              = postgres.ColumnList{}
	)

	return analyzedCompaniesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                    IDColumn,
		CompanyID:             CompanyIDColumn,
		ExtractedAttachmentID: ExtractedAttachmentIDColumn,
		Path:                  PathColumn,
		CreatedAt:             CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
