//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Announcements = newAnnouncementsTable("public", "announcements", "")

type announcementsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	CompanyID postgres.ColumnString
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AnnouncementsTable struct {
	announcementsTable

	EXCLUDED announcementsTable
}

// AS creates new AnnouncementsTable with assigned alias
func (a AnnouncementsTable) AS(alias string) *AnnouncementsTable {
	return newAnnouncementsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AnnouncementsTable with assigned schema name
func (a AnnouncementsTable) FromSchema(schemaName string) *AnnouncementsTable {
	return newAnnouncementsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AnnouncementsTable with assigned table prefix
func (a AnnouncementsTable) WithPrefix(prefix string) *AnnouncementsTable {
	return newAnnouncementsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AnnouncementsTable with assigned table suffix
func (a AnnouncementsTable) WithSuffix(suffix string) *AnnouncementsTable {
	return newAnnouncementsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAnnouncementsTable(schemaName, tableName, alias string) *AnnouncementsTable {
	return &AnnouncementsTable{
		announcementsTable: newAnnouncementsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAnnouncementsTableImpl("", "excluded", ""),
	}
}

func newAnnouncementsTableImpl(schemaName, tableName, alias string) announcementsTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		CompanyIDColumn = postgres.StringColumn("company_id")
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, CompanyIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CompanyIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return announcementsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CompanyID: CompanyIDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
