//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Attachments = newAttachmentsTable("public", "attachments", "")

type attachmentsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	AnnouncementID postgres.ColumnString
	Name           postgres.ColumnString
	Path           postgres.ColumnString
	Checksum       postgres.ColumnString
	SourceURL      postgres.ColumnString
	Type           postgres.ColumnString
	PublishedAt    postgres.ColumnTimestampz
	CreatedAt      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AttachmentsTable struct {
	attachmentsTable

	EXCLUDED attachmentsTable
}

// AS creates new AttachmentsTable with assigned alias
func (a AttachmentsTable) AS(alias string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AttachmentsTable with assigned schema name
func (a AttachmentsTable) FromSchema(schemaName string) *AttachmentsTable {
	return newAttachmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AttachmentsTable with assigned table prefix
func (a AttachmentsTable) WithPrefix(prefix string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AttachmentsTable with assigned table suffix
func (a AttachmentsTable) WithSuffix(suffix string) *AttachmentsTable {
	return newAttachmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAttachmentsTable(schemaName, tableName, alias string) *AttachmentsTable {
	return &AttachmentsTable{
		attachmentsTable: newAttachmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newAttachmentsTableImpl("", "excluded", ""),
	}
}

func newAttachmentsTableImpl(schemaName, tableName, alias string) attachmentsTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		AnnouncementIDColumn = postgres.StringColumn("announcement_id")
		NameColumn           = postgres.StringColumn("name")
		PathColumn           = postgres.StringColumn("path")
		ChecksumColumn       = postgres.StringColumn("checksum")
		SourceURLColumn      = postgres.StringColumn("source_url")
		TypeColumn           = postgres.StringColumn("type")
		PublishedAtColumn    = postgres.TimestampzColumn("published_at")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		allColumns           = postgres.ColumnList{IDColumn, AnnouncementIDColumn, NameColumn, PathColumn, ChecksumColumn, SourceURLColumn, TypeColumn, PublishedAtColumn, CreatedAtColumn}
		mutableColumns       = postgres.ColumnList{AnnouncementIDColumn, NameColumn, PathColumn, ChecksumColumn, SourceURLColumn, TypeColumn, PublishedAtColumn, CreatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, TypeColumn, CreatedAtColumn}
	)

	return attachmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		AnnouncementID: AnnouncementIDColumn,
		Name:           NameColumn,
		Path:           PathColumn,
		Checksum:       ChecksumColumn,
		SourceURL:      SourceURLColumn,
		Type:           TypeColumn,
		PublishedAt:    PublishedAtColumn,
		CreatedAt:      CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
