//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Companies = newCompaniesTable("public", "companies", "")

type companiesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Name        postgres.ColumnString
	Sector      postgres.ColumnString
	SubSector   postgres.ColumnString
	Industry    postgres.ColumnString
	SubIndustry postgres.ColumnString
	Ticker      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CompaniesTable struct {
	companiesTable

	EXCLUDED companiesTable
}

// AS creates new CompaniesTable with assigned alias
func (a CompaniesTable) AS(alias string) *CompaniesTable {
	return newCompaniesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CompaniesTable with assigned schema name
func (a CompaniesTable) FromSchema(schemaName string) *CompaniesTable {
	return newCompaniesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CompaniesTable with assigned table prefix
func (a CompaniesTable) WithPrefix(prefix string) *CompaniesTable {
	return newCompaniesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CompaniesTable with assigned table suffix
func (a CompaniesTable) WithSuffix(suffix string) *CompaniesTable {
	return newCompaniesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCompaniesTable(schemaName, tableName, alias string) *CompaniesTable {
	return &CompaniesTable{
		companiesTable: newCompaniesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCompaniesTableImpl("", "excluded", ""),
	}
}

func newCompaniesTableImpl(schemaName, tableName, alias string) companiesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		NameColumn        = postgres.StringColumn("name")
		SectorColumn      = postgres.StringColumn("sector")
		SubSectorColumn   = postgres.StringColumn("sub_sector")
		IndustryColumn    = postgres.StringColumn("industry")
		SubIndustryColumn = postgres.StringColumn("sub_industry")
		TickerColumn      = postgres.StringColumn("ticker")
		allColumns        = postgres.ColumnList{IDColumn, NameColumn, SectorColumn, SubSectorColumn, IndustryColumn, SubIndustryColumn, TickerColumn}
		mutableColumns    = postgres.ColumnList{NameColumn, SectorColumn, SubSectorColumn, IndustryColumn, SubIndustryColumn, TickerColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, SectorColumn, SubSectorColumn, IndustryColumn, SubIndustryColumn}
	)

	return companiesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Sector:      SectorColumn,
		SubSector:   SubSectorColumn,
		Industry:    IndustryColumn,
		SubIndustry: SubIndustryColumn,
		Ticker:      TickerColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
