//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ExtractedAttachments = newExtractedAttachmentsTable("public", "extracted_attachments", "")

type extractedAttachmentsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	AttachmentID postgres.ColumnString
	Name         postgres.ColumnString
	Path         postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ExtractedAttachmentsTable struct {
	extractedAttachmentsTable

	EXCLUDED extractedAttachmentsTable
}

// AS creates new ExtractedAttachmentsTable with assigned alias
func (a ExtractedAttachmentsTable) AS(alias string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ExtractedAttachmentsTable with assigned schema name
func (a ExtractedAttachmentsTable) FromSchema(schemaName string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ExtractedAttachmentsTable with assigned table prefix
func (a ExtractedAttachmentsTable) WithPrefix(prefix string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ExtractedAttachmentsTable with assigned table suffix
func (a ExtractedAttachmentsTable) WithSuffix(suffix string) *ExtractedAttachmentsTable {
	return newExtractedAttachmentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newExtractedAttachmentsTable(schemaName, tableName, alias string) *ExtractedAttachmentsTable {
	return &ExtractedAttachmentsTable{
		extractedAttachmentsTable: newExtractedAttachmentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newExtractedAttachmentsTableImpl("", "excluded", ""),
	}
}

func newExtractedAttachmentsTableImpl(schemaName, tableName, alias string) extractedAttachmentsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		AttachmentIDColumn = postgres.StringColumn("attachment_id")
		NameColumn         = postgres.StringColumn("name")
		PathColumn         = postgres.StringColumn("path")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, AttachmentIDColumn, NameColumn, PathColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{AttachmentIDColumn, NameColumn, PathColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{}
	)

	return extractedAttachmentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		AttachmentID: AttachmentIDColumn,
		Name:         NameColumn,
		Path:         PathColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
