//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AttachmentType = &struct {
	PublicExpose            postgres.StringExpression
	CorpAction              postgres.StringExpression
	EarningCall             postgres.StringExpression
	Pers                    postgres.StringExpression
	SharesOwnershipsUpdate  postgres.StringExpression
	SharesOutstandingUpdate postgres.StringExpression
	Others                  postgres.StringExpression
}{
	PublicExpose:            postgres.NewEnumValue("public_expose"),
	CorpAction:              postgres.NewEnumValue("corp_action"),
	EarningCall:             postgres.NewEnumValue("earning_call"),
	Pers:                    postgres.NewEnumValue("pers"),
	SharesOwnershipsUpdate:  postgres.NewEnumValue("shares_ownerships_update"),
	SharesOutstandingUpdate: postgres.NewEnumValue("shares_outstanding_update"),
	Others:                  postgres.NewEnumValue("others"),
}
