//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var IndustryType = &struct {
	AplikasiAmpersandJasaInternet                      postgres.StringExpression
	Asuransi                                           postgres.StringExpression
	Bank                                               postgres.StringExpression
	BarangElektronikKonsumen                           postgres.StringExpression
	BarangKimia                                        postgres.StringExpression
	BarangRumahTangga                                  postgres.StringExpression
	BatuBara                                           postgres.StringExpression
	DepartmentStore                                    postgres.StringExpression
	DistributorBarangKonsumen                          postgres.StringExpression
	Farmasi                                            postgres.StringExpression
	HiburanAmpersandFilm                               postgres.StringExpression
	JasaInvestasi                                      postgres.StringExpression
	JasaKomersial                                      postgres.StringExpression
	JasaAmpersandKonsultanTi                           postgres.StringExpression
	JasaProfesional                                    postgres.StringExpression
	JasaTelekomunikasi                                 postgres.StringExpression
	JasaTelekomunikasiNirkabel                         postgres.StringExpression
	Kelistrikan                                        postgres.StringExpression
	KomponenOtomotif                                   postgres.StringExpression
	KonstruksiBangunan                                 postgres.StringExpression
	LogamAmpersandMineral                              postgres.StringExpression
	LogistikAmpersandPengantaran                       postgres.StringExpression
	MakananOlahan                                      postgres.StringExpression
	MaskapaiPenerbangan                                postgres.StringExpression
	MaterialKonstruksi                                 postgres.StringExpression
	Media                                              postgres.StringExpression
	Mesin                                              postgres.StringExpression
	Minuman                                            postgres.StringExpression
	MinyakAmpersandGas                                 postgres.StringExpression
	OperatorInfrastrukturTransportasi                  postgres.StringExpression
	PakaianAmpersandBarangMewah                        postgres.StringExpression
	PariwisataAmpersandRekreasi                        postgres.StringExpression
	PembiayaanKonsumen                                 postgres.StringExpression
	PendidikanAmpersandJasaPenunjang                   postgres.StringExpression
	PendukungMinyakCommaGasAmpersandBatuBara           postgres.StringExpression
	PengangkutanDaratPenumpang                         postgres.StringExpression
	PengelolaAmpersandPengembangRealEstat              postgres.StringExpression
	PenyediaJasaKesehatan                              postgres.StringExpression
	PeralatanEnergiAlternatif                          postgres.StringExpression
	PeralatanJaringan                                  postgres.StringExpression
	PeralatanOlahRagaAmpersandBarangHobi               postgres.StringExpression
	PeralatanAmpersandPerlengkapanKesehatan            postgres.StringExpression
	PerangkatCommaInstrumenAmpersandKomponenElektronik postgres.StringExpression
	PerangkatKomputer                                  postgres.StringExpression
	PerangkatLunak                                     postgres.StringExpression
	PerdaganganAnekaBarangPerindustrian                postgres.StringExpression
	PerdaganganRitelBarangPrimer                       postgres.StringExpression
	PerhutananAmpersandKertas                          postgres.StringExpression
	PerusahaanHoldingAmpersandInvestasi                postgres.StringExpression
	PerusahaanHoldingMultiSektor                       postgres.StringExpression
	ProdukMakananPertanian                             postgres.StringExpression
	ProdukPerawatanTubuh                               postgres.StringExpression
	ProdukAmpersandPerlengkapanBangunan                postgres.StringExpression
	RitelKhusus                                        postgres.StringExpression
	Rokok                                              postgres.StringExpression
	UtilitasGas                                        postgres.StringExpression
	UtilitasListrik                                    postgres.StringExpression
	WadahAmpersandKemasan                              postgres.StringExpression
	Others                                             postgres.StringExpression
}{
	AplikasiAmpersandJasaInternet:            postgres.NewEnumValue("Aplikasi & Jasa Internet"),
	Asuransi:                                 postgres.NewEnumValue("Asuransi"),
	Bank:                                     postgres.NewEnumValue("Bank"),
	BarangElektronikKonsumen:                 postgres.NewEnumValue("Barang Elektronik Konsumen"),
	BarangKimia:                              postgres.NewEnumValue("Barang Kimia"),
	BarangRumahTangga:                        postgres.NewEnumValue("Barang Rumah Tangga"),
	BatuBara:                                 postgres.NewEnumValue("Batu Bara"),
	DepartmentStore:                          postgres.NewEnumValue("Department Store"),
	DistributorBarangKonsumen:                postgres.NewEnumValue("Distributor Barang Konsumen"),
	Farmasi:                                  postgres.NewEnumValue("Farmasi"),
	HiburanAmpersandFilm:                     postgres.NewEnumValue("Hiburan & Film"),
	JasaInvestasi:                            postgres.NewEnumValue("Jasa Investasi"),
	JasaKomersial:                            postgres.NewEnumValue("Jasa Komersial"),
	JasaAmpersandKonsultanTi:                 postgres.NewEnumValue("Jasa & Konsultan TI"),
	JasaProfesional:                          postgres.NewEnumValue("Jasa Profesional"),
	JasaTelekomunikasi:                       postgres.NewEnumValue("Jasa Telekomunikasi"),
	JasaTelekomunikasiNirkabel:               postgres.NewEnumValue("Jasa Telekomunikasi Nirkabel"),
	Kelistrikan:                              postgres.NewEnumValue("Kelistrikan"),
	KomponenOtomotif:                         postgres.NewEnumValue("Komponen Otomotif"),
	KonstruksiBangunan:                       postgres.NewEnumValue("Konstruksi Bangunan"),
	LogamAmpersandMineral:                    postgres.NewEnumValue("Logam & Mineral"),
	LogistikAmpersandPengantaran:             postgres.NewEnumValue("Logistik & Pengantaran"),
	MakananOlahan:                            postgres.NewEnumValue("Makanan Olahan"),
	MaskapaiPenerbangan:                      postgres.NewEnumValue("Maskapai Penerbangan"),
	MaterialKonstruksi:                       postgres.NewEnumValue("Material Konstruksi"),
	Media:                                    postgres.NewEnumValue("Media"),
	Mesin:                                    postgres.NewEnumValue("Mesin"),
	Minuman:                                  postgres.NewEnumValue("Minuman"),
	MinyakAmpersandGas:                       postgres.NewEnumValue("Minyak & Gas"),
	OperatorInfrastrukturTransportasi:        postgres.NewEnumValue("Operator Infrastruktur Transportasi"),
	PakaianAmpersandBarangMewah:              postgres.NewEnumValue("Pakaian & Barang Mewah"),
	PariwisataAmpersandRekreasi:              postgres.NewEnumValue("Pariwisata & Rekreasi"),
	PembiayaanKonsumen:                       postgres.NewEnumValue("Pembiayaan Konsumen"),
	PendidikanAmpersandJasaPenunjang:         postgres.NewEnumValue("Pendidikan & Jasa Penunjang"),
	PendukungMinyakCommaGasAmpersandBatuBara: postgres.NewEnumValue("Pendukung Minyak, Gas & Batu Bara"),
	PengangkutanDaratPenumpang:               postgres.NewEnumValue("Pengangkutan Darat Penumpang"),
	PengelolaAmpersandPengembangRealEstat:    postgres.NewEnumValue("Pengelola & Pengembang Real Estat"),
	PenyediaJasaKesehatan:                    postgres.NewEnumValue("Penyedia Jasa Kesehatan"),
	PeralatanEnergiAlternatif:                postgres.NewEnumValue("Peralatan Energi Alternatif"),
	PeralatanJaringan:                        postgres.NewEnumValue("Peralatan Jaringan"),
	PeralatanOlahRagaAmpersandBarangHobi:     postgres.NewEnumValue("Peralatan Olah Raga & Barang Hobi"),
	PeralatanAmpersandPerlengkapanKesehatan:  postgres.NewEnumValue("Peralatan & Perlengkapan Kesehatan"),
	PerangkatCommaInstrumenAmpersandKomponenElektronik: postgres.NewEnumValue("Perangkat, Instrumen & Komponen Elektronik"),
	PerangkatKomputer:                   postgres.NewEnumValue("Perangkat Komputer"),
	PerangkatLunak:                      postgres.NewEnumValue("Perangkat Lunak"),
	PerdaganganAnekaBarangPerindustrian: postgres.NewEnumValue("Perdagangan Aneka Barang Perindustrian"),
	PerdaganganRitelBarangPrimer:        postgres.NewEnumValue("Perdagangan Ritel Barang Primer"),
	PerhutananAmpersandKertas:           postgres.NewEnumValue("Perhutanan & Kertas"),
	PerusahaanHoldingAmpersandInvestasi: postgres.NewEnumValue("Perusahaan Holding & Investasi"),
	PerusahaanHoldingMultiSektor:        postgres.NewEnumValue("Perusahaan Holding Multi-sektor"),
	ProdukMakananPertanian:              postgres.NewEnumValue("Produk Makanan Pertanian"),
	ProdukPerawatanTubuh:                postgres.NewEnumValue("Produk Perawatan Tubuh"),
	ProdukAmpersandPerlengkapanBangunan: postgres.NewEnumValue("Produk & Perlengkapan Bangunan"),
	RitelKhusus:                         postgres.NewEnumValue("Ritel Khusus"),
	Rokok:                               postgres.NewEnumValue("Rokok"),
	UtilitasGas:                         postgres.NewEnumValue("Utilitas Gas"),
	UtilitasListrik:                     postgres.NewEnumValue("Utilitas Listrik"),
	WadahAmpersandKemasan:               postgres.NewEnumValue("Wadah & Kemasan"),
	Others:                              postgres.NewEnumValue("Others"),
}
