//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var SectorType = &struct {
	BarangBaku                    postgres.StringExpression
	BarangKonsumenNonPrimer       postgres.StringExpression
	BarangKonsumenPrimer          postgres.StringExpression
	Energi                        postgres.StringExpression
	Infrastruktur                 postgres.StringExpression
	Kesehatan                     postgres.StringExpression
	Keuangan                      postgres.StringExpression
	Perindustrian                 postgres.StringExpression
	PropertiAmpersandRealEstat    postgres.StringExpression
	Teknologi                     postgres.StringExpression
	TransportasiAmpersandLogistik postgres.StringExpression
	Others                        postgres.StringExpression
}{
	BarangBaku:                    postgres.NewEnumValue("Barang Baku"),
	BarangKonsumenNonPrimer:       postgres.NewEnumValue("Barang Konsumen Non-Primer"),
	BarangKonsumenPrimer:          postgres.NewEnumValue("Barang Konsumen Primer"),
	Energi:                        postgres.NewEnumValue("Energi"),
	Infrastruktur:                 postgres.NewEnumValue("Infrastruktur"),
	Kesehatan:                     postgres.NewEnumValue("Kesehatan"),
	Keuangan:                      postgres.NewEnumValue("Keuangan"),
	Perindustrian:                 postgres.NewEnumValue("Perindustrian"),
	PropertiAmpersandRealEstat:    postgres.NewEnumValue("Properti & Real Estat"),
	Teknologi:                     postgres.NewEnumValue("Teknologi"),
	TransportasiAmpersandLogistik: postgres.NewEnumValue("Transportasi & Logistik"),
	Others:                        postgres.NewEnumValue("Others"),
}
