//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var SubSectorType = &struct {
	Asuransi                                  postgres.StringExpression
	Bank                                      postgres.StringExpression
	BarangBaku                                postgres.StringExpression
	BarangPerindustrian                       postgres.StringExpression
	BarangRekreasi                            postgres.StringExpression
	BarangRumahTangga                         postgres.StringExpression
	EnergiAlternatif                          postgres.StringExpression
	FarmasiAmpersandRisetKesehatan            postgres.StringExpression
	InfrastrukturTransportasi                 postgres.StringExpression
	JasaInvestasi                             postgres.StringExpression
	JasaKonsumen                              postgres.StringExpression
	JasaPembiayaan                            postgres.StringExpression
	JasaAmpersandPeralatanKesehatan           postgres.StringExpression
	JasaPerindustrian                         postgres.StringExpression
	KonstruksiBangunan                        postgres.StringExpression
	LogistikAmpersandPengantaran              postgres.StringExpression
	MakananAmpersandMinuman                   postgres.StringExpression
	MediaAmpersandHiburan                     postgres.StringExpression
	MinyakCommaGasAmpersandBatuBara           postgres.StringExpression
	OtomotifAmpersandKomponenOtomotif         postgres.StringExpression
	PakaianAmpersandBarangMewah               postgres.StringExpression
	PerangkatKerasAmpersandPeralatanTeknologi postgres.StringExpression
	PerangkatLunakAmpersandJasaTi             postgres.StringExpression
	PerdaganganRitel                          postgres.StringExpression
	PerdaganganRitelBarangPrimer              postgres.StringExpression
	PerusahaanHoldingAmpersandInvestasi       postgres.StringExpression
	PerusahaanHoldingMultiSektor              postgres.StringExpression
	ProdukRumahTanggaTidakTahanLama           postgres.StringExpression
	PropertiAmpersandRealEstat                postgres.StringExpression
	Rokok                                     postgres.StringExpression
	Telekomunikasi                            postgres.StringExpression
	Transportasi                              postgres.StringExpression
	Utilitas                                  postgres.StringExpression
	Others                                    postgres.StringExpression
}{
	Asuransi:                                  postgres.NewEnumValue("Asuransi"),
	Bank:                                      postgres.NewEnumValue("Bank"),
	BarangBaku:                                postgres.NewEnumValue("Barang Baku"),
	BarangPerindustrian:                       postgres.NewEnumValue("Barang Perindustrian"),
	BarangRekreasi:                            postgres.NewEnumValue("Barang Rekreasi"),
	BarangRumahTangga:                         postgres.NewEnumValue("Barang Rumah Tangga"),
	EnergiAlternatif:                          postgres.NewEnumValue("Energi Alternatif"),
	FarmasiAmpersandRisetKesehatan:            postgres.NewEnumValue("Farmasi & Riset Kesehatan"),
	InfrastrukturTransportasi:                 postgres.NewEnumValue("Infrastruktur Transportasi"),
	JasaInvestasi:                             postgres.NewEnumValue("Jasa Investasi"),
	JasaKonsumen:                              postgres.NewEnumValue("Jasa Konsumen"),
	JasaPembiayaan:                            postgres.NewEnumValue("Jasa Pembiayaan"),
	JasaAmpersandPeralatanKesehatan:           postgres.NewEnumValue("Jasa & Peralatan Kesehatan"),
	JasaPerindustrian:                         postgres.NewEnumValue("Jasa Perindustrian"),
	KonstruksiBangunan:                        postgres.NewEnumValue("Konstruksi Bangunan"),
	LogistikAmpersandPengantaran:              postgres.NewEnumValue("Logistik & Pengantaran"),
	MakananAmpersandMinuman:                   postgres.NewEnumValue("Makanan & Minuman"),
	MediaAmpersandHiburan:                     postgres.NewEnumValue("Media & Hiburan"),
	MinyakCommaGasAmpersandBatuBara:           postgres.NewEnumValue("Minyak, Gas & Batu Bara"),
	OtomotifAmpersandKomponenOtomotif:         postgres.NewEnumValue("Otomotif & Komponen Otomotif"),
	PakaianAmpersandBarangMewah:               postgres.NewEnumValue("Pakaian & Barang Mewah"),
	PerangkatKerasAmpersandPeralatanTeknologi: postgres.NewEnumValue("Perangkat Keras & Peralatan Teknologi"),
	PerangkatLunakAmpersandJasaTi:             postgres.NewEnumValue("Perangkat Lunak & Jasa TI"),
	PerdaganganRitel:                          postgres.NewEnumValue("Perdagangan Ritel"),
	PerdaganganRitelBarangPrimer:              postgres.NewEnumValue("Perdagangan Ritel Barang Primer"),
	PerusahaanHoldingAmpersandInvestasi:       postgres.NewEnumValue("Perusahaan Holding & Investasi"),
	PerusahaanHoldingMultiSektor:              postgres.NewEnumValue("Perusahaan Holding Multi Sektor"),
	ProdukRumahTanggaTidakTahanLama:           postgres.NewEnumValue("Produk Rumah Tangga Tidak Tahan Lama"),
	PropertiAmpersandRealEstat:                postgres.NewEnumValue("Properti & Real Estat"),
	Rokok:                                     postgres.NewEnumValue("Rokok"),
	Telekomunikasi:                            postgres.NewEnumValue("Telekomunikasi"),
	Transportasi:                              postgres.NewEnumValue("Transportasi"),
	Utilitas:                                  postgres.NewEnumValue("Utilitas"),
	Others:                                    postgres.NewEnumValue("Others"),
}
