//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var SubIndustryType = &struct {
	AgenPerjalanan                                           postgres.StringExpression
	AlasKaki                                                 postgres.StringExpression
	Alumunium                                                postgres.StringExpression
	AplikasiAmpersandJasaInternet                            postgres.StringExpression
	AsuransiJiwa                                             postgres.StringExpression
	AsuransiUmum                                             postgres.StringExpression
	BajaAmpersandBesi                                        postgres.StringExpression
	Ban                                                      postgres.StringExpression
	Bank                                                     postgres.StringExpression
	BankInvestasiAmpersandPerantaraPerdagangan               postgres.StringExpression
	BarangElektronikKonsumen                                 postgres.StringExpression
	BarangKimiaDasar                                         postgres.StringExpression
	BarangKimiaKhusus                                        postgres.StringExpression
	BarangKimiaPertanian                                     postgres.StringExpression
	DepartmentStore                                          postgres.StringExpression
	DistribusiBatuBara                                       postgres.StringExpression
	DistributorBarangKonsumen                                postgres.StringExpression
	Emas                                                     postgres.StringExpression
	Farmasi                                                  postgres.StringExpression
	FasilitasRekreasiAmpersandOlahRaga                       postgres.StringExpression
	HiburanAmpersandFilm                                     postgres.StringExpression
	HotelCommaResorAmpersandKapalPesiar                      postgres.StringExpression
	IkanCommaDagingAmpersandProdukUnggas                     postgres.StringExpression
	JasaAmpersandKonsultanTi                                 postgres.StringExpression
	JasaPendidikan                                           postgres.StringExpression
	JasaPendukungBisnis                                      postgres.StringExpression
	JasaPenelitianAmpersandKonsultasi                        postgres.StringExpression
	JasaPengeboranMinyakAmpersandGas                         postgres.StringExpression
	JasaPengelolaanLingkunganAmpersandSarana                 postgres.StringExpression
	JasaAmpersandPerlengkapanMinyakCommaGasAmpersandBatuBara postgres.StringExpression
	JasaPersonalia                                           postgres.StringExpression
	JasaRealEstat                                            postgres.StringExpression
	JasaTelekomunikasiKabel                                  postgres.StringExpression
	JasaTelekomunikasiNirkabel                               postgres.StringExpression
	JasaTelekomunikasiTerintegrasi                           postgres.StringExpression
	Kayu                                                     postgres.StringExpression
	Kertas                                                   postgres.StringExpression
	KomponenAmpersandPeralatanKelistrikan                    postgres.StringExpression
	KonstruksiBangunan                                       postgres.StringExpression
	LogamAmpersandMineralLainnya                             postgres.StringExpression
	LogistikAmpersandPengantaran                             postgres.StringExpression
	MakananOlahan                                            postgres.StringExpression
	ManajemenInvestasi                                       postgres.StringExpression
	MaskapaiPenerbangan                                      postgres.StringExpression
	MaterialKonstruksi                                       postgres.StringExpression
	MesinAmpersandKomponenPerindustrian                      postgres.StringExpression
	MesinKonstruksiAmpersandKendaraanBerat                   postgres.StringExpression
	MinumanKeras                                             postgres.StringExpression
	MinumanRingan                                            postgres.StringExpression
	OperatorBandarUdara                                      postgres.StringExpression
	OperatorJalanTolAmpersandRel                             postgres.StringExpression
	OperatorPelabuhan                                        postgres.StringExpression
	PakaianCommaAksesorisCommaAmpersandTas                   postgres.StringExpression
	PembiayaanKonsumen                                       postgres.StringExpression
	Penerbitan                                               postgres.StringExpression
	PengembangAmpersandOperatorRealEstat                     postgres.StringExpression
	PenyediaAmpersandDistribusiPerlengkapanKesehatan         postgres.StringExpression
	PenyediaJasaKesehatan                                    postgres.StringExpression
	Penyiaran                                                postgres.StringExpression
	PenyiaranBerbayar                                        postgres.StringExpression
	PenyimpananAmpersandDistribusiMinyakAmpersandGas         postgres.StringExpression
	PeralatanEnergiAlternatif                                postgres.StringExpression
	PeralatanJaringan                                        postgres.StringExpression
	PeralatanKantor                                          postgres.StringExpression
	PeralatanOlahRagaAmpersandBarangHobi                     postgres.StringExpression
	PeralatanRumahTangga                                     postgres.StringExpression
	PerangkatAmpersandInstrumenElektronik                    postgres.StringExpression
	PerangkatKomputer                                        postgres.StringExpression
	PerangkatLunak                                           postgres.StringExpression
	PercetakanKomersial                                      postgres.StringExpression
	PerdaganganAnekaBarangPerindustrian                      postgres.StringExpression
	Periklanan                                               postgres.StringExpression
	PerkebunanAmpersandTanamanPangan                         postgres.StringExpression
	PerlengkapanRumahTangga                                  postgres.StringExpression
	PerusahaanHoldingKeuangan                                postgres.StringExpression
	PerusahaanHoldingMultiSektor                             postgres.StringExpression
	PerusahaanInvestasi                                      postgres.StringExpression
	ProdukHutanLainnya                                       postgres.StringExpression
	ProdukPerawatanTubuh                                     postgres.StringExpression
	ProdukAmpersandPerlengkapanBangunan                      postgres.StringExpression
	ProduksiBatuBara                                         postgres.StringExpression
	ProduksiAmpersandPenyulinganMinyakAmpersandGas           postgres.StringExpression
	ProdukSusuOlahan                                         postgres.StringExpression
	ProdusenFurniturRumah                                    postgres.StringExpression
	Reasuransi                                               postgres.StringExpression
	RitelBarangRumahTangga                                   postgres.StringExpression
	RitelAmpersandDistributorMakanan                         postgres.StringExpression
	RitelAmpersandDistributorObatObatan                      postgres.StringExpression
	RitelElektronik                                          postgres.StringExpression
	RitelOtomotif                                            postgres.StringExpression
	RitelPakaianAmpersandTekstil                             postgres.StringExpression
	Rokok                                                    postgres.StringExpression
	RumahMakan                                               postgres.StringExpression
	SukuCadangOtomotif                                       postgres.StringExpression
	Supermarket                                              postgres.StringExpression
	Tekstil                                                  postgres.StringExpression
	Tembaga                                                  postgres.StringExpression
	TransportasiJalanan                                      postgres.StringExpression
	UtilitasGas                                              postgres.StringExpression
	UtilitasListrik                                          postgres.StringExpression
	WadahAmpersandKemasan                                    postgres.StringExpression
	Others                                                   postgres.StringExpression
}{
	AgenPerjalanan:                postgres.NewEnumValue("Agen Perjalanan"),
	AlasKaki:                      postgres.NewEnumValue("Alas Kaki"),
	Alumunium:                     postgres.NewEnumValue("Alumunium"),
	AplikasiAmpersandJasaInternet: postgres.NewEnumValue("Aplikasi & Jasa Internet"),
	AsuransiJiwa:                  postgres.NewEnumValue("Asuransi Jiwa"),
	AsuransiUmum:                  postgres.NewEnumValue("Asuransi Umum"),
	BajaAmpersandBesi:             postgres.NewEnumValue("Baja & Besi"),
	Ban:                           postgres.NewEnumValue("Ban"),
	Bank:                          postgres.NewEnumValue("Bank"),
	BankInvestasiAmpersandPerantaraPerdagangan: postgres.NewEnumValue("Bank Investasi & Perantara Perdagangan"),
	BarangElektronikKonsumen:                   postgres.NewEnumValue("Barang Elektronik Konsumen"),
	BarangKimiaDasar:                           postgres.NewEnumValue("Barang Kimia Dasar"),
	BarangKimiaKhusus:                          postgres.NewEnumValue("Barang Kimia Khusus"),
	BarangKimiaPertanian:                       postgres.NewEnumValue("Barang Kimia Pertanian"),
	DepartmentStore:                            postgres.NewEnumValue("Department Store"),
	DistribusiBatuBara:                         postgres.NewEnumValue("Distribusi Batu Bara"),
	DistributorBarangKonsumen:                  postgres.NewEnumValue("Distributor Barang Konsumen"),
	Emas:                                       postgres.NewEnumValue("Emas"),
	Farmasi:                                    postgres.NewEnumValue("Farmasi"),
	FasilitasRekreasiAmpersandOlahRaga:         postgres.NewEnumValue("Fasilitas Rekreasi & Olah Raga"),
	HiburanAmpersandFilm:                       postgres.NewEnumValue("Hiburan & Film"),
	HotelCommaResorAmpersandKapalPesiar:        postgres.NewEnumValue("Hotel, Resor & Kapal Pesiar"),
	IkanCommaDagingAmpersandProdukUnggas:       postgres.NewEnumValue("Ikan, Daging & Produk Unggas"),
	JasaAmpersandKonsultanTi:                   postgres.NewEnumValue("Jasa & Konsultan TI"),
	JasaPendidikan:                             postgres.NewEnumValue("Jasa Pendidikan"),
	JasaPendukungBisnis:                        postgres.NewEnumValue("Jasa Pendukung Bisnis"),
	JasaPenelitianAmpersandKonsultasi:          postgres.NewEnumValue("Jasa Penelitian & Konsultasi"),
	JasaPengeboranMinyakAmpersandGas:           postgres.NewEnumValue("Jasa Pengeboran Minyak & Gas"),
	JasaPengelolaanLingkunganAmpersandSarana:   postgres.NewEnumValue("Jasa Pengelolaan Lingkungan & Sarana"),
	JasaAmpersandPerlengkapanMinyakCommaGasAmpersandBatuBara: postgres.NewEnumValue("Jasa & Perlengkapan Minyak, Gas & Batu Bara"),
	JasaPersonalia:                         postgres.NewEnumValue("Jasa Personalia"),
	JasaRealEstat:                          postgres.NewEnumValue("Jasa Real Estat"),
	JasaTelekomunikasiKabel:                postgres.NewEnumValue("Jasa Telekomunikasi Kabel"),
	JasaTelekomunikasiNirkabel:             postgres.NewEnumValue("Jasa Telekomunikasi Nirkabel"),
	JasaTelekomunikasiTerintegrasi:         postgres.NewEnumValue("Jasa Telekomunikasi Terintegrasi"),
	Kayu:                                   postgres.NewEnumValue("Kayu"),
	Kertas:                                 postgres.NewEnumValue("Kertas"),
	KomponenAmpersandPeralatanKelistrikan:  postgres.NewEnumValue("Komponen & Peralatan Kelistrikan"),
	KonstruksiBangunan:                     postgres.NewEnumValue("Konstruksi Bangunan"),
	LogamAmpersandMineralLainnya:           postgres.NewEnumValue("Logam & Mineral Lainnya"),
	LogistikAmpersandPengantaran:           postgres.NewEnumValue("Logistik & Pengantaran"),
	MakananOlahan:                          postgres.NewEnumValue("Makanan Olahan"),
	ManajemenInvestasi:                     postgres.NewEnumValue("Manajemen Investasi"),
	MaskapaiPenerbangan:                    postgres.NewEnumValue("Maskapai Penerbangan"),
	MaterialKonstruksi:                     postgres.NewEnumValue("Material Konstruksi"),
	MesinAmpersandKomponenPerindustrian:    postgres.NewEnumValue("Mesin & Komponen Perindustrian"),
	MesinKonstruksiAmpersandKendaraanBerat: postgres.NewEnumValue("Mesin Konstruksi & Kendaraan Berat"),
	MinumanKeras:                           postgres.NewEnumValue("Minuman Keras"),
	MinumanRingan:                          postgres.NewEnumValue("Minuman Ringan"),
	OperatorBandarUdara:                    postgres.NewEnumValue("Operator Bandar Udara"),
	OperatorJalanTolAmpersandRel:           postgres.NewEnumValue("Operator Jalan Tol & Rel"),
	OperatorPelabuhan:                      postgres.NewEnumValue("Operator Pelabuhan"),
	PakaianCommaAksesorisCommaAmpersandTas: postgres.NewEnumValue("Pakaian, Aksesoris, & Tas"),
	PembiayaanKonsumen:                     postgres.NewEnumValue("Pembiayaan Konsumen"),
	Penerbitan:                             postgres.NewEnumValue("Penerbitan"),
	PengembangAmpersandOperatorRealEstat:   postgres.NewEnumValue("Pengembang & Operator Real Estat"),
	PenyediaAmpersandDistribusiPerlengkapanKesehatan: postgres.NewEnumValue("Penyedia & Distribusi Perlengkapan Kesehatan"),
	PenyediaJasaKesehatan:                            postgres.NewEnumValue("Penyedia Jasa Kesehatan"),
	Penyiaran:                                        postgres.NewEnumValue("Penyiaran"),
	PenyiaranBerbayar:                                postgres.NewEnumValue("Penyiaran Berbayar"),
	PenyimpananAmpersandDistribusiMinyakAmpersandGas: postgres.NewEnumValue("Penyimpanan & Distribusi Minyak & Gas"),
	PeralatanEnergiAlternatif:                        postgres.NewEnumValue("Peralatan Energi Alternatif"),
	PeralatanJaringan:                                postgres.NewEnumValue("Peralatan Jaringan"),
	PeralatanKantor:                                  postgres.NewEnumValue("Peralatan Kantor"),
	PeralatanOlahRagaAmpersandBarangHobi:             postgres.NewEnumValue("Peralatan Olah Raga & Barang Hobi"),
	PeralatanRumahTangga:                             postgres.NewEnumValue("Peralatan Rumah Tangga"),
	PerangkatAmpersandInstrumenElektronik:            postgres.NewEnumValue("Perangkat & Instrumen Elektronik"),
	PerangkatKomputer:                                postgres.NewEnumValue("Perangkat Komputer"),
	PerangkatLunak:                                   postgres.NewEnumValue("Perangkat Lunak"),
	PercetakanKomersial:                              postgres.NewEnumValue("Percetakan Komersial"),
	PerdaganganAnekaBarangPerindustrian:              postgres.NewEnumValue("Perdagangan Aneka Barang Perindustrian"),
	Periklanan:                                       postgres.NewEnumValue("Periklanan"),
	PerkebunanAmpersandTanamanPangan:                 postgres.NewEnumValue("Perkebunan & Tanaman Pangan"),
	PerlengkapanRumahTangga:                          postgres.NewEnumValue("Perlengkapan Rumah Tangga"),
	PerusahaanHoldingKeuangan:                        postgres.NewEnumValue("Perusahaan Holding Keuangan"),
	PerusahaanHoldingMultiSektor:                     postgres.NewEnumValue("Perusahaan Holding Multi-sektor"),
	PerusahaanInvestasi:                              postgres.NewEnumValue("Perusahaan Investasi"),
	ProdukHutanLainnya:                               postgres.NewEnumValue("Produk Hutan Lainnya"),
	ProdukPerawatanTubuh:                             postgres.NewEnumValue("Produk Perawatan Tubuh"),
	ProdukAmpersandPerlengkapanBangunan:              postgres.NewEnumValue("Produk & Perlengkapan Bangunan"),
	ProduksiBatuBara:                                 postgres.NewEnumValue("Produksi Batu Bara"),
	ProduksiAmpersandPenyulinganMinyakAmpersandGas:   postgres.NewEnumValue("Produksi & Penyulingan Minyak & Gas"),
	ProdukSusuOlahan:                                 postgres.NewEnumValue("Produk Susu Olahan"),
	ProdusenFurniturRumah:                            postgres.NewEnumValue("Produsen Furnitur Rumah"),
	Reasuransi:                                       postgres.NewEnumValue("Reasuransi"),
	RitelBarangRumahTangga:                           postgres.NewEnumValue("Ritel Barang Rumah Tangga"),
	RitelAmpersandDistributorMakanan:                 postgres.NewEnumValue("Ritel & Distributor Makanan"),
	RitelAmpersandDistributorObatObatan:              postgres.NewEnumValue("Ritel & Distributor Obat-obatan"),
	RitelElektronik:                                  postgres.NewEnumValue("Ritel Elektronik"),
	RitelOtomotif:                                    postgres.NewEnumValue("Ritel Otomotif"),
	RitelPakaianAmpersandTekstil:                     postgres.NewEnumValue("Ritel Pakaian & Tekstil"),
	Rokok:                                            postgres.NewEnumValue("Rokok"),
	RumahMakan:                                       postgres.NewEnumValue("Rumah Makan"),
	SukuCadangOtomotif:                               postgres.NewEnumValue("Suku Cadang Otomotif"),
	Supermarket:                                      postgres.NewEnumValue("Supermarket"),
	Tekstil:                                          postgres.NewEnumValue("Tekstil"),
	Tembaga:                                          postgres.NewEnumValue("Tembaga"),
	TransportasiJalanan:                              postgres.NewEnumValue("Transportasi Jalanan"),
	UtilitasGas:                                      postgres.NewEnumValue("Utilitas Gas"),
	UtilitasListrik:                                  postgres.NewEnumValue("Utilitas Listrik"),
	WadahAmpersandKemasan:                            postgres.NewEnumValue("Wadah & Kemasan"),
	Others:                                           postgres.NewEnumValue("Others"),
}
