Table announcements {
  id text [pk]
  stock_code varchar(4)
  announcement_date timestamptz
  announcement_title text
  processed_at timestamptz [default: `now()`]
  
  Note: 'Metadata for processed IDX announcements'
}

Table attachments {
  id uuid [pk, default: `uuidv7()`]
  announcement_id text [ref: > announcements.id]
  original_filename text
  checksum text
  storage_path text
  uploaded_at timestamptz [default: `now()`, note: 'timestamptz when it is uploaded to s3']
  
  Note: 'Files uploaded to S3'
  
  indexes {
    (announcement_id, original_filename) [unique]
  }
}
