// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: nil.sql

package sql

import (
	"context"
)

const getCompanies = `-- name: GetCompanies :many
SELECT id, name, ticker FROM companies
`

func (q *Queries) GetCompanies(ctx context.Context) ([]Companies, error) {
	rows, err := q.db.Query(ctx, getCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Companies
	for rows.Next() {
		var i Companies
		if err := rows.Scan(&i.ID, &i.Name, &i.Ticker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
