// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sql

import (
	"context"
)

type Querier interface {
	GetCompanies(ctx context.Context) ([]Companies, error)
}

var _ Querier = (*Queries)(nil)
