// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"context"

	"github.com/alturino/bloodhound/internal/db/.gen/bloodhound/public/model"
	"github.com/alturino/bloodhound/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIDXStore creates a new instance of MockIDXStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDXStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDXStore {
	mock := &MockIDXStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDXStore is an autogenerated mock type for the IDXStore type
type MockIDXStore struct {
	mock.Mock
}

type MockIDXStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDXStore) EXPECT() *MockIDXStore_Expecter {
	return &MockIDXStore_Expecter{mock: &_m.Mock}
}

// Announcement provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) Announcement(ctx context.Context, id ...string) ([]model.Announcements, error) {
	var tmpRet mock.Arguments
	if len(id) > 0 {
		tmpRet = _mock.Called(ctx, id)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Announcement")
	}

	var r0 []model.Announcements
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]model.Announcements, error)); ok {
		return returnFunc(ctx, id...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []model.Announcements); ok {
		r0 = returnFunc(ctx, id...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Announcements)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, id...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDXStore_Announcement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Announcement'
type MockIDXStore_Announcement_Call struct {
	*mock.Call
}

// Announcement is a helper method to define mock.On call
//   - ctx context.Context
//   - id ...string
func (_e *MockIDXStore_Expecter) Announcement(ctx interface{}, id ...interface{}) *MockIDXStore_Announcement_Call {
	return &MockIDXStore_Announcement_Call{Call: _e.mock.On("Announcement",
		append([]interface{}{ctx}, id...)...)}
}

func (_c *MockIDXStore_Announcement_Call) Run(run func(ctx context.Context, id ...string)) *MockIDXStore_Announcement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIDXStore_Announcement_Call) Return(announcementss []model.Announcements, err error) *MockIDXStore_Announcement_Call {
	_c.Call.Return(announcementss, err)
	return _c
}

func (_c *MockIDXStore_Announcement_Call) RunAndReturn(run func(ctx context.Context, id ...string) ([]model.Announcements, error)) *MockIDXStore_Announcement_Call {
	_c.Call.Return(run)
	return _c
}

// Attachment provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) Attachment(ctx context.Context, storagepath ...string) (model.Attachments, error) {
	var tmpRet mock.Arguments
	if len(storagepath) > 0 {
		tmpRet = _mock.Called(ctx, storagepath)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Attachment")
	}

	var r0 model.Attachments
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (model.Attachments, error)); ok {
		return returnFunc(ctx, storagepath...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) model.Attachments); ok {
		r0 = returnFunc(ctx, storagepath...)
	} else {
		r0 = ret.Get(0).(model.Attachments)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, storagepath...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDXStore_Attachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attachment'
type MockIDXStore_Attachment_Call struct {
	*mock.Call
}

// Attachment is a helper method to define mock.On call
//   - ctx context.Context
//   - storagepath ...string
func (_e *MockIDXStore_Expecter) Attachment(ctx interface{}, storagepath ...interface{}) *MockIDXStore_Attachment_Call {
	return &MockIDXStore_Attachment_Call{Call: _e.mock.On("Attachment",
		append([]interface{}{ctx}, storagepath...)...)}
}

func (_c *MockIDXStore_Attachment_Call) Run(run func(ctx context.Context, storagepath ...string)) *MockIDXStore_Attachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIDXStore_Attachment_Call) Return(attachments model.Attachments, err error) *MockIDXStore_Attachment_Call {
	_c.Call.Return(attachments, err)
	return _c
}

func (_c *MockIDXStore_Attachment_Call) RunAndReturn(run func(ctx context.Context, storagepath ...string) (model.Attachments, error)) *MockIDXStore_Attachment_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimAttachments provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) ClaimAttachments(ctx context.Context, ids []uuid.UUID) error {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ClaimAttachments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDXStore_ClaimAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimAttachments'
type MockIDXStore_ClaimAttachments_Call struct {
	*mock.Call
}

// ClaimAttachments is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockIDXStore_Expecter) ClaimAttachments(ctx interface{}, ids interface{}) *MockIDXStore_ClaimAttachments_Call {
	return &MockIDXStore_ClaimAttachments_Call{Call: _e.mock.On("ClaimAttachments", ctx, ids)}
}

func (_c *MockIDXStore_ClaimAttachments_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockIDXStore_ClaimAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDXStore_ClaimAttachments_Call) Return(err error) *MockIDXStore_ClaimAttachments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDXStore_ClaimAttachments_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) error) *MockIDXStore_ClaimAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessedAttachments provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) GetUnprocessedAttachments(ctx context.Context) ([]model.Attachments, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessedAttachments")
	}

	var r0 []model.Attachments
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Attachments, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Attachments); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Attachments)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDXStore_GetUnprocessedAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessedAttachments'
type MockIDXStore_GetUnprocessedAttachments_Call struct {
	*mock.Call
}

// GetUnprocessedAttachments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDXStore_Expecter) GetUnprocessedAttachments(ctx interface{}) *MockIDXStore_GetUnprocessedAttachments_Call {
	return &MockIDXStore_GetUnprocessedAttachments_Call{Call: _e.mock.On("GetUnprocessedAttachments", ctx)}
}

func (_c *MockIDXStore_GetUnprocessedAttachments_Call) Run(run func(ctx context.Context)) *MockIDXStore_GetUnprocessedAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDXStore_GetUnprocessedAttachments_Call) Return(attachmentss []model.Attachments, err error) *MockIDXStore_GetUnprocessedAttachments_Call {
	_c.Call.Return(attachmentss, err)
	return _c
}

func (_c *MockIDXStore_GetUnprocessedAttachments_Call) RunAndReturn(run func(ctx context.Context) ([]model.Attachments, error)) *MockIDXStore_GetUnprocessedAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAnnouncement provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) InsertAnnouncement(ctx context.Context, ann models.Announcement) error {
	ret := _mock.Called(ctx, ann)

	if len(ret) == 0 {
		panic("no return value specified for InsertAnnouncement")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Announcement) error); ok {
		r0 = returnFunc(ctx, ann)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDXStore_InsertAnnouncement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAnnouncement'
type MockIDXStore_InsertAnnouncement_Call struct {
	*mock.Call
}

// InsertAnnouncement is a helper method to define mock.On call
//   - ctx context.Context
//   - ann models.Announcement
func (_e *MockIDXStore_Expecter) InsertAnnouncement(ctx interface{}, ann interface{}) *MockIDXStore_InsertAnnouncement_Call {
	return &MockIDXStore_InsertAnnouncement_Call{Call: _e.mock.On("InsertAnnouncement", ctx, ann)}
}

func (_c *MockIDXStore_InsertAnnouncement_Call) Run(run func(ctx context.Context, ann models.Announcement)) *MockIDXStore_InsertAnnouncement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Announcement
		if args[1] != nil {
			arg1 = args[1].(models.Announcement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDXStore_InsertAnnouncement_Call) Return(err error) *MockIDXStore_InsertAnnouncement_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDXStore_InsertAnnouncement_Call) RunAndReturn(run func(ctx context.Context, ann models.Announcement) error) *MockIDXStore_InsertAnnouncement_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAnnouncements provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) InsertAnnouncements(ctx context.Context, anns []models.Announcement) error {
	ret := _mock.Called(ctx, anns)

	if len(ret) == 0 {
		panic("no return value specified for InsertAnnouncements")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.Announcement) error); ok {
		r0 = returnFunc(ctx, anns)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDXStore_InsertAnnouncements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAnnouncements'
type MockIDXStore_InsertAnnouncements_Call struct {
	*mock.Call
}

// InsertAnnouncements is a helper method to define mock.On call
//   - ctx context.Context
//   - anns []models.Announcement
func (_e *MockIDXStore_Expecter) InsertAnnouncements(ctx interface{}, anns interface{}) *MockIDXStore_InsertAnnouncements_Call {
	return &MockIDXStore_InsertAnnouncements_Call{Call: _e.mock.On("InsertAnnouncements", ctx, anns)}
}

func (_c *MockIDXStore_InsertAnnouncements_Call) Run(run func(ctx context.Context, anns []models.Announcement)) *MockIDXStore_InsertAnnouncements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.Announcement
		if args[1] != nil {
			arg1 = args[1].([]models.Announcement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDXStore_InsertAnnouncements_Call) Return(err error) *MockIDXStore_InsertAnnouncements_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDXStore_InsertAnnouncements_Call) RunAndReturn(run func(ctx context.Context, anns []models.Announcement) error) *MockIDXStore_InsertAnnouncements_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAttachment provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) InsertAttachment(ctx context.Context, attachments ...model.Attachments) error {
	var tmpRet mock.Arguments
	if len(attachments) > 0 {
		tmpRet = _mock.Called(ctx, attachments)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...model.Attachments) error); ok {
		r0 = returnFunc(ctx, attachments...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDXStore_InsertAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAttachment'
type MockIDXStore_InsertAttachment_Call struct {
	*mock.Call
}

// InsertAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - attachments ...model.Attachments
func (_e *MockIDXStore_Expecter) InsertAttachment(ctx interface{}, attachments ...interface{}) *MockIDXStore_InsertAttachment_Call {
	return &MockIDXStore_InsertAttachment_Call{Call: _e.mock.On("InsertAttachment",
		append([]interface{}{ctx}, attachments...)...)}
}

func (_c *MockIDXStore_InsertAttachment_Call) Run(run func(ctx context.Context, attachments ...model.Attachments)) *MockIDXStore_InsertAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Attachments
		var variadicArgs []model.Attachments
		if len(args) > 1 {
			variadicArgs = args[1].([]model.Attachments)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIDXStore_InsertAttachment_Call) Return(err error) *MockIDXStore_InsertAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDXStore_InsertAttachment_Call) RunAndReturn(run func(ctx context.Context, attachments ...model.Attachments) error) *MockIDXStore_InsertAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// IsExists provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) IsExists(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDXStore_IsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExists'
type MockIDXStore_IsExists_Call struct {
	*mock.Call
}

// IsExists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDXStore_Expecter) IsExists(ctx interface{}) *MockIDXStore_IsExists_Call {
	return &MockIDXStore_IsExists_Call{Call: _e.mock.On("IsExists", ctx)}
}

func (_c *MockIDXStore_IsExists_Call) Run(run func(ctx context.Context)) *MockIDXStore_IsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDXStore_IsExists_Call) Return(b bool, err error) *MockIDXStore_IsExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIDXStore_IsExists_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockIDXStore_IsExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsProcessed provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) IsProcessed(ctx context.Context, idxIDs ...string) (map[string]bool, error) {
	var tmpRet mock.Arguments
	if len(idxIDs) > 0 {
		tmpRet = _mock.Called(ctx, idxIDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for IsProcessed")
	}

	var r0 map[string]bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (map[string]bool, error)); ok {
		return returnFunc(ctx, idxIDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) map[string]bool); ok {
		r0 = returnFunc(ctx, idxIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, idxIDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDXStore_IsProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProcessed'
type MockIDXStore_IsProcessed_Call struct {
	*mock.Call
}

// IsProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - idxIDs ...string
func (_e *MockIDXStore_Expecter) IsProcessed(ctx interface{}, idxIDs ...interface{}) *MockIDXStore_IsProcessed_Call {
	return &MockIDXStore_IsProcessed_Call{Call: _e.mock.On("IsProcessed",
		append([]interface{}{ctx}, idxIDs...)...)}
}

func (_c *MockIDXStore_IsProcessed_Call) Run(run func(ctx context.Context, idxIDs ...string)) *MockIDXStore_IsProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockIDXStore_IsProcessed_Call) Return(stringToBool map[string]bool, err error) *MockIDXStore_IsProcessed_Call {
	_c.Call.Return(stringToBool, err)
	return _c
}

func (_c *MockIDXStore_IsProcessed_Call) RunAndReturn(run func(ctx context.Context, idxIDs ...string) (map[string]bool, error)) *MockIDXStore_IsProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// LatestAnnouncement provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) LatestAnnouncement(ctx context.Context) (model.Announcements, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestAnnouncement")
	}

	var r0 model.Announcements
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (model.Announcements, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) model.Announcements); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(model.Announcements)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIDXStore_LatestAnnouncement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestAnnouncement'
type MockIDXStore_LatestAnnouncement_Call struct {
	*mock.Call
}

// LatestAnnouncement is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIDXStore_Expecter) LatestAnnouncement(ctx interface{}) *MockIDXStore_LatestAnnouncement_Call {
	return &MockIDXStore_LatestAnnouncement_Call{Call: _e.mock.On("LatestAnnouncement", ctx)}
}

func (_c *MockIDXStore_LatestAnnouncement_Call) Run(run func(ctx context.Context)) *MockIDXStore_LatestAnnouncement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIDXStore_LatestAnnouncement_Call) Return(announcements model.Announcements, err error) *MockIDXStore_LatestAnnouncement_Call {
	_c.Call.Return(announcements, err)
	return _c
}

func (_c *MockIDXStore_LatestAnnouncement_Call) RunAndReturn(run func(ctx context.Context) (model.Announcements, error)) *MockIDXStore_LatestAnnouncement_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAttachmentResult provides a mock function for the type MockIDXStore
func (_mock *MockIDXStore) UpdateAttachmentResult(ctx context.Context, attachment model.Attachments) error {
	ret := _mock.Called(ctx, attachment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttachmentResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Attachments) error); ok {
		r0 = returnFunc(ctx, attachment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIDXStore_UpdateAttachmentResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAttachmentResult'
type MockIDXStore_UpdateAttachmentResult_Call struct {
	*mock.Call
}

// UpdateAttachmentResult is a helper method to define mock.On call
//   - ctx context.Context
//   - attachment model.Attachments
func (_e *MockIDXStore_Expecter) UpdateAttachmentResult(ctx interface{}, attachment interface{}) *MockIDXStore_UpdateAttachmentResult_Call {
	return &MockIDXStore_UpdateAttachmentResult_Call{Call: _e.mock.On("UpdateAttachmentResult", ctx, attachment)}
}

func (_c *MockIDXStore_UpdateAttachmentResult_Call) Run(run func(ctx context.Context, attachment model.Attachments)) *MockIDXStore_UpdateAttachmentResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Attachments
		if args[1] != nil {
			arg1 = args[1].(model.Attachments)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIDXStore_UpdateAttachmentResult_Call) Return(err error) *MockIDXStore_UpdateAttachmentResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIDXStore_UpdateAttachmentResult_Call) RunAndReturn(run func(ctx context.Context, attachment model.Attachments) error) *MockIDXStore_UpdateAttachmentResult_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockbitStore creates a new instance of MockStockbitStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockbitStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockbitStore {
	mock := &MockStockbitStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStockbitStore is an autogenerated mock type for the StockbitStore type
type MockStockbitStore struct {
	mock.Mock
}

type MockStockbitStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockbitStore) EXPECT() *MockStockbitStore_Expecter {
	return &MockStockbitStore_Expecter{mock: &_m.Mock}
}

// StockCodes provides a mock function for the type MockStockbitStore
func (_mock *MockStockbitStore) StockCodes(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StockCodes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockbitStore_StockCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StockCodes'
type MockStockbitStore_StockCodes_Call struct {
	*mock.Call
}

// StockCodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStockbitStore_Expecter) StockCodes(ctx interface{}) *MockStockbitStore_StockCodes_Call {
	return &MockStockbitStore_StockCodes_Call{Call: _e.mock.On("StockCodes", ctx)}
}

func (_c *MockStockbitStore_StockCodes_Call) Run(run func(ctx context.Context)) *MockStockbitStore_StockCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStockbitStore_StockCodes_Call) Return(strings []string, err error) *MockStockbitStore_StockCodes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockStockbitStore_StockCodes_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockStockbitStore_StockCodes_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertMarketDetector provides a mock function for the type MockStockbitStore
func (_mock *MockStockbitStore) UpsertMarketDetector(ctx context.Context, summary models.MarketDetectorSummary, transactions []models.BrokerTransaction) error {
	ret := _mock.Called(ctx, summary, transactions)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMarketDetector")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.MarketDetectorSummary, []models.BrokerTransaction) error); ok {
		r0 = returnFunc(ctx, summary, transactions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStockbitStore_UpsertMarketDetector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertMarketDetector'
type MockStockbitStore_UpsertMarketDetector_Call struct {
	*mock.Call
}

// UpsertMarketDetector is a helper method to define mock.On call
//   - ctx context.Context
//   - summary models.MarketDetectorSummary
//   - transactions []models.BrokerTransaction
func (_e *MockStockbitStore_Expecter) UpsertMarketDetector(ctx interface{}, summary interface{}, transactions interface{}) *MockStockbitStore_UpsertMarketDetector_Call {
	return &MockStockbitStore_UpsertMarketDetector_Call{Call: _e.mock.On("UpsertMarketDetector", ctx, summary, transactions)}
}

func (_c *MockStockbitStore_UpsertMarketDetector_Call) Run(run func(ctx context.Context, summary models.MarketDetectorSummary, transactions []models.BrokerTransaction)) *MockStockbitStore_UpsertMarketDetector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.MarketDetectorSummary
		if args[1] != nil {
			arg1 = args[1].(models.MarketDetectorSummary)
		}
		var arg2 []models.BrokerTransaction
		if args[2] != nil {
			arg2 = args[2].([]models.BrokerTransaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStockbitStore_UpsertMarketDetector_Call) Return(err error) *MockStockbitStore_UpsertMarketDetector_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStockbitStore_UpsertMarketDetector_Call) RunAndReturn(run func(ctx context.Context, summary models.MarketDetectorSummary, transactions []models.BrokerTransaction) error) *MockStockbitStore_UpsertMarketDetector_Call {
	_c.Call.Return(run)
	return _c
}
