package constants

const (
	AnnouncementsTotal          = "announcements_total"
	AnnouncementsCount          = "announcements_count"
	AttachmentsCount            = "attachments_count"
	PageTotal                   = "page_total"
	PageSize                    = "page_size"
	PageIdx                     = "page_idx"
	Page                        = "page"
	LatestAnnouncement          = "latest_announcement"
	LatestAnnouncementDate      = "latest_announcement_date"
	AttachmentID                = "attachment_id"
	IdxURL                      = "idx_url"
	UnprocessedAttachmentsCount = "unprocessed_attachments_count"
	UnprocessedAnnouncements    = "unprocessed_announcements"
	AttachmentSize              = "attachment_size"
	Claimed                     = "claimed"
	InsertedCount               = "inserted_count"
	SQLStatement                = "sql_statement"
	IsExists                    = "is_exists"
	CurrentTime                 = "current_time"
	ProcessedID                 = "processed_id"
	Found                       = "found"
	Attachment                  = "attachment"
	LocalSaveResult             = "local_save_res"
	MinIOResult                 = "minio_result"
	ObjectSize                  = "object_size"
	ContentType                 = "content_type"
	CleanFilepath               = "clean_filepath"
	HTTPDump                    = "http_dump"
	WorkerID                    = "worker_id"
	Interval                    = "interval"
	Symbol                      = "symbol"
	DateFrom                    = "date_from"
	DateTo                      = "date_to"
	Bucket                      = "bucket"
	File                        = "file"
	Object                      = "object"
	URL                         = "url"
	Status                      = "status"
	Service                     = "service"
	Count                        = "count"
	ExecutedAt                   = "executed_at"
)

const (
	HTTPURL          = "http.url"
	HTTPMethod       = "http.method"
	HTTPReqHeader    = "http.req.header"
	HTTPReqBody      = "http.req.body"
	HTTPReqRetry     = "http.req.retry_attempt"
	HTTPReqStartTime = "http.req.start_time"
	HTTPRespDuration = "http.resp.duration"
	HTTPRespStatus   = "http.resp.status_code"
	HTTPRespHeaders  = "http.resp.headers"
	HTTPRespEndTime  = "http.resp.end_time"
	HTTPRespBody     = "http.resp.body"
)
